### ISSUE TITLE
[Arch Linux] Can't change any controller settings

### ISSUE THREAD

**Issue by appins** [mupen64plus/mupen64plus-ui-python#100]
When I change the controller settings, it closes the entire application and I doesn't save the configuration

**Comment by gen2brain** [comment]
Are you using a latest version? Do you have some logs, anything?

**Comment by AppIns** [comment]
This is it. Not really too much useful info

[m64pylog.txt](https://github.com/mupen64plus/mupen64plus-ui-python/files/852040/m64pylog.txt)

**Comment by gen2brain** [comment]
There is an info that you are not using latest version. Try with 0.2.4

**Comment by AppIns** [comment]
Updated, now I have a separate issue and I can't even check if this one is still there... XD

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
