### ISSUE TITLE
Closes as soon as I start ROM

### ISSUE THREAD

**Issue by ItsBunny** [mupen64plus/mupen64plus-ui-python#105]
I go to file, open ROM, manually, I click on the ROM and then the window turns black for a split second and then it just closes with no message or anything.

**Comment by gen2brain** [comment]
What OS, what version, what video plugin are you using? Anything in log, does it happens with all games etc.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
