### ISSUE TITLE
dummy plugins cannot be used

### ISSUE THREAD

**Issue by Papermanzero** [mupen64plus/mupen64plus-ui-python#106]
If the users delete a plugin, mupen64plus shall fall back to dummy plugins.
However m64py is crashing if a plugin is missing (for instance audio).
Means, if the users deletes all audio plugins, m64py cannot select any alternative, then the emulator crashes either if the users tries to start a game or if the users wants to open the plugin settings.

**Comment by gen2brain** [comment]
This should be fixed in f617b4b0be5e8581a0f5c83e1d46c454ac4e56dc . Not exactly a solution where you can select "dummy" but it will not crash.

**Comment by Papermanzero** [comment]
Thanks @gen2brain 
Do you have a developer build?
I would like to test an issue concerning performance.
https://github.com/gonetz/GLideN64/issues/470#issuecomment-299810150

It would be great to see, if also the performance issue is gone with the dummy plugin, or if the root cause is somewhere else.

**Comment by gen2brain** [comment]
No problem. You need build for windows? I can build one now, but I need to start vmware.

**Comment by Papermanzero** [comment]
Yes, a windows build would be perfect. Thanks a lot for the support!

**Comment by gen2brain** [comment]
Ok, you can try with these builds:
http://81.4.106.254/m64py-0.2.5-setup.exe
http://81.4.106.254/m64py-0.2.5-portable.zip

**Comment by Papermanzero** [comment]
@gen2brain 
Thanks again. I tried the version, but unfortunately it is not working.
It always shows a pop up during boot "failed to execute script m64py"
I tried both builds.

**Comment by gen2brain** [comment]
This should be fixed in c3a037f7b66842c516b7a223976bb05f91946379 .
New Windows builds are here:
http://81.4.106.254/m64py-0.2.5-setup.exe
http://81.4.106.254/m64py-0.2.5-portable.zip
http://81.4.106.254/m64py-0.2.5-setup-console.exe
http://81.4.106.254/m64py-0.2.5-portable-console.zip
