### ISSUE TITLE
M64py crahes when opening ROM on windows

### ISSUE THREAD

**Issue by nachomendi2** [mupen64plus/mupen64plus-ui-python#108]
I'm really new to m64py so i dont know too much about it, i just downloaded it from The website for Windows and installed it with The installer, when i open The test ROM from  mupen64plus it works just fine, but when i try to open a game ir just closes without any report. Using Windows 7

**Comment by nachomendi2** [comment]
Much* it*  fine*, sorry i'm writing from The phone and autocorrect doesn't help

**Comment by gen2brain** [comment]
This should be fixed in c3a037f7b66842c516b7a223976bb05f91946379 .
New Windows builds are here:
http://81.4.106.254/m64py-0.2.5-setup.exe
http://81.4.106.254/m64py-0.2.5-portable.zip
http://81.4.106.254/m64py-0.2.5-setup-console.exe
http://81.4.106.254/m64py-0.2.5-portable-console.zip

**Comment by gen2brain** [comment]
Can you try with these builds, use console versions to see errors:
http://81.4.106.254/m64py-0.2.5-setup.exe
http://81.4.106.254/m64py-0.2.5-portable.zip
http://81.4.106.254/m64py-0.2.5-setup-console.exe
http://81.4.106.254/m64py-0.2.5-portable-console.zip

**Comment by kenzierocks** [comment]
I have this same problem, running Windows 10 (version 1709, build 16299.248) and using the portable console version linked above, I got this when opening a SM64 ROM, right after the intro: https://gist.github.com/kenzierocks/57462c520a539bb0a1cc0041cd597cc4

The test ROM works great.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
