### ISSUE TITLE
PS4 Controller Issues

### ISSUE THREAD

**Issue by Phant0mD3mon** [mupen64plus/mupen64plus-ui-python#109]
I have been using my PS4 controller on my Mac on many other programs with very few issues. However, I have had a string of issues on M64Py. First off, it would detect my controller in the controls menu, but if I bound one button, as soon as I tried to bind another button, it would immediately set itself to the button I bound last. As far as I could tell, there was no way to fix this in the program itself. So, following in what many people were doing with their unrelated issues, I decided to edit InputAutoCfg.ini. I bound it to controls I found online that seemed to be alright, but now the controller is not detected in-game. Side note: I never tested to see if the controller was detected in-game before editing the .ini file, if that helps. Also, I have been connecting it through a USB cable connected to a USB to Thunderbolt 3 connector, if that means anything. Any help is appreciated!

**Comment by Marc34** [comment]
This is not the only controller with issues. It is impossible to use FC30 PRO. Configuring the input plugin has no effect.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
