### ISSUE TITLE
ImportError: No module named QtOpenGL

### ISSUE THREAD

**Issue by YalithKBK** [mupen64plus/mupen64plus-ui-python#114]
As similar to issue #32 I get an import error. As there isn't a solution in that issue, I opened another. Below is my traceback. So far as I know, I have all of the dependencies installed, but I could be wrong.  

```
M64Py - A frontend for Mupen64Plus version 0.2.4

Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
Traceback (most recent call last):
  File "./m64py", line 57, in <module>
    from m64py.frontend.mainwindow import MainWindow
  File "/home/yalith/Downloads/m64py-0.2.4/src/m64py/frontend/mainwindow.py", line 30, in <module>
    from m64py.frontend.worker import Worker
  File "/home/yalith/Downloads/m64py-0.2.4/src/m64py/frontend/worker.py", line 27, in <module>
    from m64py.core.core import Core
  File "/home/yalith/Downloads/m64py-0.2.4/src/m64py/core/core.py", line 31, in <module>
    from m64py.core.vidext import vidext
  File "/home/yalith/Downloads/m64py-0.2.4/src/m64py/core/vidext.py", line 26, in <module>
    from PyQt5.QtOpenGL import QGLFormat
ImportError: No module named QtOpenGL
```

m64py does not open, just gives me this error.

**Comment by autofire372** [comment]
This is a _little_ late, but are you sure you installed the right version of PyQt5OpenGL? I ran into the same issue on Linux Mint, and it turned out I needed the Python**3** version of that dependency (if you're running Ubuntu or something based on it like Mint, the package is python3-pyqt5.qtopengl).

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
