### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by someguy235464758** [mupen64plus/mupen64plus-ui-python#116]
1 the installer sets user as root so i can't change the shortcut to run in terminal to display output because it tells me i don't have permission
2 terminal says the program doesn't exist
3 program does not launch
{right clicking should give option for the action run in terminal but actions tab is empty}

**Comment by robalni** [comment]
**1**

How did you install? Can you describe all the steps?

What do you mean by "the shortcut"?

**2**

You can search for the program file with this command:

```
sudo updatedb; locate m64py | grep bin
```
