### ISSUE TITLE
(Arch Linux) Controls do not work after upgrading to 0.2.4

### ISSUE THREAD

**Issue by Abello966** [mupen64plus/mupen64plus-ui-python#125]
I was having trouble with the program crashing after trying to alter the controller settings so I upgraded to m64py 0.2.5. The bug has been fixed but now no input is read by the emulator. Using pure mupen64plus seems to work fine however
Attaching typical log of execution
[log.txt](https://github.com/mupen64plus/mupen64plus-ui-python/files/1877361/log.txt)

**Comment by frealgagu** [comment]
The current version for mupen64plus-ui-python is 0.2.4, are you talking about mupen64plus version 2.4?

**Comment by Abello966** [comment]
Oh sorry, I had git cloned it and probably got a more recent version that's still experimental
yet, when I use the latest release (0.2.4) the problem persists

**Comment by frealgagu** [comment]
Something that happens to me is that after save the control configuration weird characters (&) appears in the buttons name in the file. Once I remove the & everything works as expected. May be that what happen to you also?

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
