### ISSUE TITLE
Segfault on attempting to access any item in the settings menu (e.g plugins or paths)

### ISSUE THREAD

**Issue by ghost** [mupen64plus/mupen64plus-ui-python#128]
Preface: I installed the frontend from the arch user repository, following the sourceforge source list lead me here, ergo here I post.

installed via:

>pacaur -S m64py-git

tried m64py (non-git version) but it failed with ImportError: cannot import name 'Ui_LicenseDialog'

> M64Py - A frontend for Mupen64Plus version 0.2.5
> 
> Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0
> Frontend: INFO: includes support for Dynamic Recompiler.
> Frontend: INFO: video extension enabled
> Unhandled Python exception
> [1]    509 abort (core dumped)  m64py --verbose

I would try to debug the 'where' and 'why' for the exception but my python familiarity is extremely shallow to put it generously.

This, by extension, makes me unable to actually use the frontend since without settings I get this

> Core: No video plugin attached.  There will be no video output.
> Core: No RSP plugin attached.  The video output will be corrupted.
> Core: No audio plugin attached.  There will be no sound output.
> Core: No input plugin attached.  You won't be able to control the game.
> [1]    452 segmentation fault (core dumped)  m64py

I can provide some cursory debugging if instructions are provided, I could not figure out how to use the python debugger (and gdb didn't even want to try) so I cannot currently provide more than this. Verbose output (--verbose)

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
