### ISSUE TITLE
Crash on assigning keypad key 5 (with numlock off) both on Windows and Linux

### ISSUE THREAD

**Issue by fastrizwaan** [mupen64plus/mupen64plus-ui-python#129]
rizvan@solus4 ~/.rizvan.at.office.grive $ m64py 
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.4

Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0
Frontend: INFO: includes support for Dynamic Recompiler.
Frontend: INFO: video extension enabled
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/m64py/ui/inputbutton.py", line 69, in keyPressEvent
    text = SDL_GetScancodeName(QT2SDL2[key])
KeyError: 16777227
Aborted

**Comment by gen2brain** [comment]
Handled in https://github.com/mupen64plus/mupen64plus-ui-python/commit/8b3e4f033a853758f9054867f737416ce1a14da0 . It will not crash anymore when we don't handle key in keymap.
