### ISSUE TITLE
[Windows 10] M64Py v0.2.4 Setup (CreateProcess failed; code 5)

### ISSUE THREAD

**Issue by DarkWolf4564** [mupen64plus/mupen64plus-ui-python#136]
Ok, Brand New Laptop... And I've been trying to figure out how to "Install" mupen64/mupen64plus, but having problems, obviously. I heard that M64Py comes with the emulator & the ui. But every time I try to install it, I get this message immediately after installing - 
![capture](https://user-images.githubusercontent.com/29392190/46263356-ba725a00-c4d3-11e8-9df8-b08dff18e033.PNG)

I don't think my computer specs would help, so I'm just gonna wait until I get further information.

Also every time I try to install a Emulator (~Dolphin~, 1964, ~Project64~, & regular mupen64) this pops up - 
![capture2](https://user-images.githubusercontent.com/29392190/46263410-6b78f480-c4d4-11e8-9e33-390eed9f9538.PNG)

**Comment by gen2brain** [comment]
Hi, you can try with portable version, just unpack zip to your home dir https://github.com/mupen64plus/mupen64plus-ui-python/releases/download/0.2.4/m64py-0.2.4-portable.zip  .

You can try again with installer but try to run as administrator or similar, not sure how that works now in newer Windows versions.

**Comment by DarkWolf4564** [comment]
*Unpacked zip to Home Dir
*Clicked on m64py, it disappears
*Deleted Folder. Then Unpacked it again.
*Clicked mupen64plus, got the "no SDL2.dll" message. Then clicked on m64py again, it disappears
*Deleted Folder, & Unpacked again.
*Clicked on Installer, it still gives the "CreateProcess failed; code 5" message

So... No Progress was made. Not sure what else to do...

**Comment by HarryTheTurtle** [comment]
Looks like your default security setting may be denying access to run the executable. Did you try running the .exe as an administrator?

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
