### ISSUE TITLE
m64py portable?

### ISSUE THREAD

**Issue by Makaque** [mupen64plus/mupen64plus-ui-python#138]
Since Project 64 can be made fully portable one thing I like to do is bundle all plugins, configuration, everything together with one ROM, make a shortcut, and treat that bundle like a standalone game. It's saved me the headache of messing with configuration while switching between games. I can just set it and forget it. 

m64py doesn't seem to search the executable directory for configuration at any point, and simply creates a config file in the QSettings default location if it's missing. Could this functionality be added?

**Comment by gen2brain** [comment]
You can try with portable build https://github.com/mupen64plus/mupen64plus-ui-python/releases/download/0.2.4/m64py-0.2.4-portable.zip . That build just changes some config paths to current working dir, see here https://github.com/mupen64plus/mupen64plus-ui-python/blob/master/setup.py#L307 .

**Comment by Makaque** [comment]
Thanks, that looks promising. Is there a Linux version though? I'm trying to set up an old laptop as a retro game machine.

I suppose this depends on whether there's a portable version of the mupen64plus core for Linux as well.

**Comment by gen2brain** [comment]
There is no Linux version, portable zip is built from setup.py here https://github.com/mupen64plus/mupen64plus-ui-python/blob/master/setup.py#L307 , and it replaces path in core.py and settings.py, you can do the same for Linux.

No need for portable core I think, ConfigPath and DataPath can be passed to CoreStartup function (that is the line setup.py modifies to build portable zip).

**Comment by Makaque** [comment]
Built the program with your suggested changes. Configured the mupen64plu.cfg file to use relative paths in the current directory. Set up an executable bash script for each game to act as a shortcut that changes the current working directory to the location of the m64py executable, then launches. Now everything is working quite well. Every game gets its own instance and they can each be launched with their own shortcut.

I feel like this could also be changed to use the m64py executable file path instead of the current working directory so that it could be launched with a symbolic link and wouldn't need the bash script. I might play around with this a bit more. But this is a good, working solution. Thanks for the help.
