### ISSUE TITLE
M64py crahes when opening ROM on windows 10

### ISSUE THREAD

**Issue by lemur616** [mupen64plus/mupen64plus-ui-python#142]
Greetings:
I am new on the use of M64py, so I do not know much about it. The issue is that whenever I try to load a ROM with it, my screen goes black for a moment and then I am back to desktop without any notice or warning. I have tried with the test ROM and it works, so I am not sure what is the problme here. My OS is Windows 10 home single language. My pc has a Intel core I7 6700 at 3.40 Ghz, 16 Gb of ram and a Nvidia 1070 with 16 Gb of vram. I have used the M64py 0.2.4. version. Used both the exe and portable versions of it.

**Comment by lemur616** [comment]
I have found the issue. The rice video plugin is the one that causes the crash. I do not know why it happens but once I changed the plugin to glide. The app worked fine.

**Comment by TtruK** [comment]
Hello N64 Fans,
I installed M64PY V0.2.4 on my WIN10 Ultrabook but i have the same problem: crahes when opening ROM!

I tried all different plugins. I also tried to find the "console version" to find the error but i wasn´t able to download/find the console version .

My PC:
WIN 10 1909 64bit
INtel HD 520+ AMD FirePro W4190M
i7-6500U
8gb RAM

Hope someone knows what to do ;-)

**Comment by richard42** [comment]
Here is a link to the official release notice of mupen64plus 2.5.9 from last year, with instructions for running the console interface in Windows:

[emulatk](http://www.emutalk.net/threads/57227-Mupen64Plus-v2-5-9-Beta-Release)
