### ISSUE TITLE
Cannot Load ROM Lists?

### ISSUE THREAD

**Issue by HarryTheTurtle** [mupen64plus/mupen64plus-ui-python#143]
I have set my path to the folder containing my N64 games but the list is always empty even after refreshing the list.

Any ideas?

**Comment by gen2brain** [comment]
Anything in the log maybe? Are ROMs compressed and in what format, and on what OS?

**Comment by HarryTheTurtle** [comment]
No there is nothing in the log to indicate a problem. All the ROMS are uncompressed as .N64 files and I am running on Windows 10.
