### ISSUE TITLE
Pressing Hotkey to Pause Emulation Causes Problems

### ISSUE THREAD

**Issue by HarryTheTurtle** [mupen64plus/mupen64plus-ui-python#144]
If the emulated game is currently the active window, pressing the hotkey for pause will pause the game like it should. Pressing the hot key again will not unpause the emulation. If the m64py GUI is currently the active window then the game emulation window will pause normally and unpause normally if the pause hotkey is pressed. If I press the hotkey to pause the emulation with m64py window active and it pauses and then I click the emulation window to make it active it will no longer unpause. Worse yet, the paused and active emulation window will now be frozen in place meaning you can't move it aside to make the m64py window active to unpause.

Can anyone else verify this is happening?

Windows 10
NVIDIA GTX 960

**Comment by thenoobtester** [comment]
I have this on linux too, when i press p it pauses the emulation but never restart it. Ctrl-C doesn't even work in the terminal to kill it i have to use kill -9 pidof mupen64Plus

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
