### ISSUE TITLE
Won't start at all.

### ISSUE THREAD

**Issue by IanWalley** [mupen64plus/mupen64plus-ui-python#145]
on windows 10, when i try to start the program, i get "error loading python DLL: C:\Program Files(x86)\M64Py\python35.dll (error code 193)"

 i tried installing microsoft visual studio redistributable 2015, and i installed PyQt5 and PySDL2. still nothing.

**Comment by gen2brain** [comment]
If you already have Python and libraries installed you can try to download sources, copy bin/m64py to root dir and try to run it from source dir. Those libraries don't affect in any way binary you are trying to use.

I am very busy currently but will try to publish a release with new mupen64plus libs. Not sure when, probably some weekend.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
