### ISSUE TITLE
Can't override video extension

### ISSUE THREAD

**Issue by rmkraus** [mupen64plus/mupen64plus-ui-python#149]
I've been my head against this one pretty hard, but I am currently stuck. When  I launch the GUI, everything works, except the video output opens in a new window. That window cannot be resized or made fullscreen.

I've tracked the issue down to this in the log:
Frontend: DEBUG: override_vidext()
Frontend: WARNING: INPUT_INVALID: An input function parameter is logically invalid

It appears that m64py is not able to [replace the Mupen64Plus core video extension](https://github.com/mupen64plus/mupen64plus-ui-python/blob/master/src/m64py/core/core.py#L492) causing the video to not be intercepted. Google was not helpful with this error.

Any help would be appreciated. I'm trying to make an addon for this library to make a machine learning platform. Could be fun.

**Comment by rmkraus** [comment]
I figured out something...

In the python ui, [vidext.Functions is set to 11.](https://github.com/mupen64plus/mupen64plus-ui-python/blob/master/src/m64py/core/vidext.py#L177)
The core, as of 2 years ago, [requires if to be 12 or higher](https://github.com/mupen64plus/mupen64plus-core/blame/2dcb6f96f723221099e36db902e130866e3b78b6/src/api/vidext.c#L58).

Simply changing the Functions value from 11 to 12 did not seem to resolve my problem however. I no longer get the error in the log, but the video output is still in its own window.

**Comment by gen2brain** [comment]
It should be fixed in https://github.com/mupen64plus/mupen64plus-ui-python/commit/5bd8fcfa977f48ee6110cdda0955b65c0c5bfd35 .

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
