### ISSUE TITLE
m64py crashes with "Unhandled Python exception"

### ISSUE THREAD

**Issue by aserranoh** [mupen64plus/mupen64plus-ui-python#150]
m64py crashes with "Unhandled Python exception" when trying to open any menu item in the menu "Settings". As soon as you click "Paths", "Emulator", "Graphics" or "Plugins" the application crashes without opening any settings window. The error visible at the end of the console output is "Unhandled Python exception":

LANG=en_US.UTF8 m64py -v
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.4

Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
Frontend: INFO: No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.9
Frontend: INFO: includes support for Dynamic Recompiler.
Core: Couldn't open configuration file '/root/.config/mupen64plus/mupen64plus.cfg'.  Using defaults.
Core: No version number in 'Core' config section. Setting defaults.
Core: No version number in 'CoreEvents' config section. Setting defaults.
Core: Using full mem base
Frontend: DEBUG: override_vidext()
Frontend: WARNING: INPUT_INVALID: An input function parameter is logically invalid
RSP: No version number in 'Rsp-HLE' config section. Setting defaults.
Video: Getting value card_id
Video: Getting value force_polygon_offset
Video: Getting value polygon_offset_factor
Video: Getting value polygon_offset_units
Video: Getting value autoframeskip
Video: Getting value maxframeskip
Video: Getting value vsync
Video: Getting value ssformat
Video: Getting value show_fps
Video: Getting value clock
Video: Getting value clock_24_hr
Video: Getting value wrpResolution
Video: Getting value wrpVRAM
Video: Getting value wrpFBO
Video: Getting value wrpAnisotropic
Video: Getting value alt_tex_size
Video: Getting value use_sts1_only
Video: Getting value force_calc_sphere
Video: Getting value correct_viewport
Video: Getting value increase_texrect_edge
Video: Getting value decrease_fillrect_edge
Video: Getting value texture_correction
Video: Getting value pal230
Video: Getting value stipple_mode
Video: Getting value stipple_pattern
Video: Getting value force_microcheck
Video: Getting value force_quad3d
Video: Getting value clip_zmin
Video: Getting value clip_zmax
Video: Getting value fast_crc
Video: Getting value adjust_aspect
Video: Getting value zmode_compare_less
Video: Getting value old_style_adither
Video: Getting value n64_z_scale
Video: Getting value optimize_texrect
Video: Getting value ignore_aux_copy
Video: Getting value hires_buf_clear
Video: Getting value fb_read_alpha
Video: Getting value useless_is_useless
Video: Getting value fb_crc_mode
Video: Getting value filtering
Video: Getting value fog
Video: Getting value buff_clear
Video: Getting value swapmode
Video: Getting value aspect
Video: Getting value lodmode
Video: Getting value fb_smart
Video: Getting value fb_hires
Video: Getting value fb_read_always
Video: Getting value read_back_to_screen
Video: Getting value detect_cpu_write
Video: Getting value fb_get_info
Video: Getting value fb_render
Video: No version number in 'Rice-Video' config section. Setting defaults.
Video: Old parameter config version detected : 0, updating to 1;
Audio: No version number in 'Audio-SDL' config section. Setting defaults.
Input: Missing or incompatible config section 'Input-SDL-Control1'. Clearing.
Input: Missing or incompatible config section 'Input-SDL-Control2'. Clearing.
Input: Missing or incompatible config section 'Input-SDL-Control3'. Clearing.
Input: Missing or incompatible config section 'Input-SDL-Control4'. Clearing.
Input: Using auto-config file at: '/usr/share/mupen64plus/InputAutoCfg.ini'
Unhandled Python exception
Abortado

I have installed the version 0.2.4 distributed by Gentoo.

**Comment by aserranoh** [comment]
I have had some time to trace the source of the error and it looks it's crashing in this line (method get_parameter_help of file config.py):

rval = self.m64p.ConfigGetParameterHelp(
            self.config_handle, C.c_char_p(param_name.encode()))

**Comment by ps4gentoo** [comment]
same here

**Comment by tbigot** [comment]
same here, Mageia

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.

**Comment by fcolecumberri** [comment]
I had a very similar problem (could be same problem), I am also using gentoo and for some reason now `/dev/input/js0` is owned by the `input` (I am almost sure that before it was owned by `plugdev` or `usb`, but not sure) and my user was not, so adding my user to the group fixed the problem.
