### ISSUE TITLE
Inputs aren't being detected after input change (M64py)

### ISSUE THREAD

**Issue by Zed-GH** [mupen64plus/mupen64plus-ui-python#151]
So, I got Mupen64 running on its own, so I installed m64py, which also worked fine. I then decided I wanted to change my controls, so I did just that. After a few minutes of tinkering I had a good setup, so I launched SM64 again, to find that I couldnt get past the title screen, due to the fact that my start button (enter) wasnt being recognized. I closed SM64, switched the start button to M, and tried again. No difference.   I openned the logs to see if anything is wrong with my controller (keyboard) being detected, and it recognizes my keyboard, but inputs arent being accepted. Due to the fact that I cant get past the title screen, I cant test any other inputs. If it matters, I'm using a mac on 10.14.6, with Python 3, and Mupen64 version 2.5.9. If any more details are needed, just tell me.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
