### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by MattKercher** [mupen64plus/mupen64plus-ui-python#153]
We haven't seen an update in quite a while. The program doesn't work on most distros anymore. Should we give up hope and settle for the disaster dumpster fire that is RetroArch? Please send help.

**Comment by gen2brain** [comment]
Not abandoned, just going very slowly. Any help is always welcomed. There will be a new release, just need to see now how to compile also for Windows, before there were automated builds that were used. Also, need to rebuild everything for macOS, and include GLideN64 plugin, etc.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
