### ISSUE TITLE
v0.2.4 on Mac, controller doesn't work

### ISSUE THREAD

**Issue by SeanHayes** [mupen64plus/mupen64plus-ui-python#155]
I have a USB adapter for a real N64 controller plugged in. When I switch the input from keyboard to joystick I can configure the buttons by either choosing auto or choosing manual and pressing the buttons. When I start a game the controller doesn't work though, and after leaving the game the settings seem to revert to keyboard.

**Comment by gen2brain** [comment]
v0.2.5 will be released in a couple of days, so you can try with that one when it is released. That should be fixed now.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open new issue if it is not resolved.
