### ISSUE TITLE
No module named setuptools 

### ISSUE THREAD

**Issue by joneldiablo** [mupen64plus/mupen64plus-ui-python#157]
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    import setuptools
ImportError: No module named setuptools

**Comment by gen2brain** [comment]
Just install python-setuptools or python3-setuptools, or with `pip install setuptools`, etc.

**Comment by Cooper-Pilot** [comment]
`sudo apt-get install python3-setuptools` should be included as steps to follow (dependencies) for debian/ubuntu and their equivalents for other distros.

**Comment by mon0theist** [comment]
Same issue, confirmed I have python3-setuptools and all the rest of the dependencies installed, still telling me "no module named setuptools"

**Comment by codywohlers** [comment]
I had to use `python**3** setup.py build` which also needed `sudo apt install qttools5-dev-tools` to get it installed on KDE Neon 5.20
