### ISSUE TITLE
(Arch Linux) Unhandled Python Exception when loading recent roms or roms from list

### ISSUE THREAD

**Issue by cjbrick910** [mupen64plus/mupen64plus-ui-python#160]
Hello,
I've been having trouble with m64py recently when my roms stopped loading from the list or the recent roms menu. The roms works just fine using the `mupen64plus`  cli, so I know it's not an emulator issue. Additionally, games work when opening them manually, just not through the roms list. There is no indication in the output, whether in verbose mode or not.

Some info about my system:
ArchLinux Kernel 5.6.7
M64Py version 0.2.5-1
Mupen64plus version 2.5-15
Python version 3.8.2
For input, I use an Xbox 360 wireless controller, though it works in the cli so I'm not sure it's pertinent.

here is the application output:
```
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.5

Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0
Frontend: INFO: includes support for Dynamic Recompiler.
Frontend: INFO: video extension enabled
Unhandled Python exception
Aborted (core dumped)
```
I am willing to provide any more information that helps solve this issue.
Thanks!

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
