### ISSUE TITLE
"Mupen64 library not found"

### ISSUE THREAD

**Issue by ThePrimeOfAllPrimes** [mupen64plus/mupen64plus-ui-python#161]
Every so often I try to load a rom and m64py crashes. I look through the settings and all of the paths are cleared. I've set the library back to the proper .dylib and it sets the others but its becoming tedious. Is there a reason or anyway I can fix this? It does not allow me to open any roms which all work as I've used them earlier in the day and in the past.

**Comment by gen2brain** [comment]
So every time it crashes it also breaks plist file in Library/Preferences, can you confirm that, so you actually rebuild that file when you manually point the library?
More info is needed, i.e. some output when it crashes. You can just cd to .app from the terminal, that is just a directory, and start m64py.sh from there, so you can see error messages when it crashes.

**Comment by ThePrimeOfAllPrimes** [comment]
The crashes are inconsistent and are usually fixed by me filling in the pathway for the library file int the paths tab. However, I tried this time and the rom runs as I can hear audio but I cannot see the visuals. Im using the glide64mk2 plugin as it worked the best in the past but now none are working. 

I am running Road Rash 64
With the log viewer I get this.
Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.9
Frontend: INFO: includes support for Dynamic Recompiler.
Core: Using full mem base
Frontend: INFO: video extension enabled
Core: Goodname: Road Rash 64 (U) [!]
Core: Name: ROAD RASH 64        
Core: MD5: 28C2373F6D831EEC81F6146A809E701B
Core: CRC: F050746C 247B820B
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 33554432 bytes (or 32 Mb or 256 Megabits)
Core: Version: 1444
Core: Manufacturer: Nintendo
Core: Country: USA
Video: opening /Users/ayazmanji/Desktop/M64Py.app/Contents/Resources/Glide64mk2.ini

Video: 3DNOW! detected.

Frontend: INFO: using Video plugin: 'Glide64mk2 Video Plugin' v2.5.9
Frontend: INFO: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.9
Core: input plugin did not specify a render callback; there will be no on screen display by the input plugin.
Input: 1 SDL joysticks were found.
Input: N64 Controller #1: Using manual config for SDL joystick 0
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.5.9 initialized.
Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.9
Frontend: INFO: using RSP plugin: 'Static Interpreter' v0.1.1
Core: Selected state slot: 2
Core: Using video capture backend: dummy
Core: Game controller 0 (Standard controller) has a Memory pak plugged in
Core: Game controller 1 (Standard controller) has a Memory pak plugged in
Core: Game controller 2 (Standard controller) has a Memory pak plugged in
Core: Game controller 3 (Standard controller) has a Memory pak plugged in
Core: Using CIC type X102
Video: Using TEXUMA extension.

Video: InitCombine() 
Video: extensions 
Video: initialized.
Video: 

Audio: Using resampler speex
Audio: Initializing SDL audio subsystem...
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Core: Initializing 4 RDRAM modules for a total of 8 MB
Core: Starting R4300 emulator: Dynamic Recompiler
Audio: Initializing SDL audio subsystem...
Video: ProcessRDPList ()

Video: ProcessRDPList ()

Video: ProcessRDPList () - this repeats until i force quit the emulator

**Comment by gen2brain** [comment]
You just sent output right, nothing crashed? Did you use the same plugins combination in mupen64plus as in m64py? And please try some else, not glide64mk2, a not in combination with static interpreter, try rsp-hle, dynamic, with rice or gliden64 plugin, something known to work, not all combinations work with all plugins.
