### ISSUE TITLE
Mac OSX App Not Opening

### ISSUE THREAD

**Issue by mwnj** [mupen64plus/mupen64plus-ui-python#166]
Made a simple download of M64py 2.5 because of your new support for gliden64. With no other apps running in the background, I tried to open the .app but it immediately closed.

2.3 worked great

**Comment by gen2brain** [comment]
I will need more info. .app is just a directory, start terminal, and cd to app contents and start m64py.sh from there and paste the output here.

**Comment by mwnj** [comment]
[573] Error loading Python lib '/Volumes/dmg/M64Py.app/Contents/MacOS/Python': dlopen: dlopen(/Volumes/dmg/M64Py.app/Contents/MacOS/Python, 10): Symbol not found: _clock_getres
  Referenced from: /Volumes/dmg/M64Py.app/Contents/MacOS/Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Volumes/dmg/M64Py.app/Contents/MacOS/Python

Thanks for the quick help!

**Comment by gen2brain** [comment]
What version of macOS are you using?

**Comment by mwnj** [comment]
Good question. 10.11.3 El Capitan

**Comment by gen2brain** [comment]
This seems to be related to pyinstaller, which is used to pack python code to binary. The simple solution is to just create binary on an older system, mupen64plus is compiled for minimum version 10.10, so Yosemite would be ok for that, matches perfectly. 

This will take a while, I have a couple of newer macOS images, but now have problems with VMware crashing on browse button when I want to install Yosemite, totally unrelated but I must fix that first.

**Comment by gen2brain** [comment]
Ok, it seems on Yosemite brew doesn't work anymore, I will just check the minimum requirements for a brew and build on that version, that should work.

**Comment by Diegopie007** [comment]
as this been fixed? i can't open the application, i'm running mac os 10.11.6

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
