### ISSUE TITLE
Options unavailable when attached to latest mupen64plus-core

### ISSUE THREAD

**Issue by Zixiken** [mupen64plus/mupen64plus-ui-python#167]
I've pulled and built the latest commit of mupen64plus-core (b7b56fe) since I had [an issue](https://github.com/mupen64plus/mupen64plus-core/issues/641#issuecomment-634937449) with the 2.5.9 release. The built library fixes that issue and I can run ROMs, however the options in the top menus that start greyed-out / unavailable remain so, and their hotkeys also don't work. Additionally, quitting or the close window button after a ROM has been started causes a seg fault.

OS linux Mint 19, kernel 5.3.0-51-generic
Processor AMD Phenom(tm) II X6 1100T
GFX Radeon HD 7700/7800 Series
More info on request

Not sure where to go with debugging this. Is this an issue with m64py, or the core library?

**Comment by gen2brain** [comment]
See this issue https://github.com/mupen64plus/mupen64plus-ui-python/issues/158, which seems related. I do not see it is in any way related to crashes you experienced before etc.

**Comment by Zixiken** [comment]
Ah, I think you're on to something here. In mint package management are versions 2.5.0 of core and plugins, and it finishes initializing before that 2 second timer. But when I switch to the latest versions that I've built, initialization hasn't finished when the timer expires, so core_state_query(M64CORE_EMU_STATE) returns M64EMU_STOPPED.
