### ISSUE TITLE
M64py crashes in startup after changed rice plugin to GlideN64 on OSX.

### ISSUE THREAD

**Issue by faruolo** [mupen64plus/mupen64plus-ui-python#170]
After i did a test using the other plugins i cannot load any rom. the M64py freezes after Mupen64plus started appears.

How can i reset the settings to default? i deleted every single file related to Mupen64 but it seems to have saved my profile settings and i cant find it anywhere on mac.

**Comment by gen2brain** [comment]
Delete plist file from your `~/Library/Preferences`.

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
