### ISSUE TITLE
i can't input

### ISSUE THREAD

**Issue by kweonsunho** [mupen64plus/mupen64plus-ui-python#172]
i can't input on m64py, but i can input on m64plus original.
my os is arch linux.
this is log.
Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0
Frontend: INFO: includes support for Dynamic Recompiler.
Frontend: INFO: video extension enabled
Core: Goodname: Super Mario 64 (U) [!]
Core: Name: SUPER MARIO 64      
Core: MD5: 20B854B239203BAF6C961B850A4A51A2
Core: CRC: 635A2BFF 8B022326
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 8388608 bytes (or 8 Mb or 64 Megabits)
Core: Version: 1444
Core: Manufacturer: Nintendo
Core: Country: USA
Frontend: INFO: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.5.0
Frontend: INFO: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Using manual config with no SDL joystick (keyboard/mouse only)
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
Frontend: INFO: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Video: SSE processing enabled.
Video: Found ROM 'SUPER MARIO 64', CRC ff2b5a632623028b-45
Video: Initializing OpenGL Device Context.
Video: Using OpenGL: X.Org - AMD RAVEN (DRM 3.37.0, 5.7.4-arch1-1, LLVM 10.0.0) : 4.6 (Compatibility Profile) Mesa 20.1.1
Audio: Initializing SDL audio subsystem...
Input: Couldn't grab input! Mouse support won't work!
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7f45fa2c6a80

**Comment by gen2brain** [comment]
By cannot input, do you mean joystick doesn't work, or keyboard? Is it "plugged" in config?

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
