### ISSUE TITLE
Xbox controller

### ISSUE THREAD

**Issue by odinissecure6** [mupen64plus/mupen64plus-ui-python#175]
I can't be the first person to have this issue, but I am not finding a fix (specifically for m64py) on any forum. 

I have mupen64plus and m64py. Inside of m64py I am configuring the input settings to use my xbox controller as controller 2. I go all the way through the setup, then go to play the game, and my controller is not working. I go back to configure the input, and its like it never saved my keys. I attempted this many times and still never a working solution. No 'save' button and also reverts back to the keyboard setup upon exiting the config.

**Comment by Unounited** [comment]
Try configuring the controlls manualy, by going to the input auto config file and edit the controls there.

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
