### ISSUE TITLE
Error while executing "python setup.py build"

### ISSUE THREAD

**Issue by pythonaddict** [mupen64plus/mupen64plus-ui-python#178]
I have Windows 10 64-bit, Python 3.9 64 bit.

I installed PyQt5 with:

`pip install PyQt5`

I'm trying to built **mupen64plus-ui-python** in cmd with: 

`python setup.py build`

But I get:

```
running build
running build_qt
error: [WinError 2] The system cannot find the file specified
```

How can I fix it?

**Comment by CHJ85** [comment]
You can't, as this program is built for python (outdated) and not python3.

**Comment by gen2brain** [comment]
@CHJ85  "program" is not built. nor is outdated, what did you mean by that? There are binaries for people that want to try and use it, and then there is the source for people that know how to build it, but nothing is "built".

**Comment by CHJ85** [comment]
I mean the program has to be updated to python3.
