### ISSUE TITLE
Switch to Qt5

### ISSUE THREAD

**Issue by ghost** [mupen64plus/mupen64plus-ui-python#18]
Qt4 isn't maintained anymore since over a year. So please switch to Qt5 to make it possible to ship it in the future distributions.

It seems that some distributions (Debian) are already planning to drop Qt4: http://perezmeyer.blogspot.de/2014/09/qt5-in-jessie-we-will-release-with-532.html

**Comment by Droogans** [comment]
I just built this in Qt5 and can confirm it works.

Is this issue still valid? Seems fixed to me.
