### ISSUE TITLE
How to bind any control? 

### ISSUE THREAD

**Issue by addeps3** [mupen64plus/mupen64plus-ui-python#181]
Hello, Im on Fedora 33 and have run the pip command from the Readme, then the build, and finally the install command, with the --user flag. 

I dont see any menu for setting keybindings. I dont have a controller plugged in, but I was hoping to set the mouse or atleast the keyboard bindings. 

Am I missing a dependency or is it supposed to be this way? 

This app seems promising, greetings, /Addie.

**Comment by JakobDev** [comment]
Go to Settings>Plugins>Input>Configure
