### ISSUE TITLE
Cannont install In Linux Ubuntu 20.04 python 3.8

### ISSUE THREAD

**Issue by hyperJJmaster** [mupen64plus/mupen64plus-ui-python#184]
running install
running bdist_egg
running egg_info
writing src/m64py.egg-info/PKG-INFO
writing dependency_links to src/m64py.egg-info/dependency_links.txt
writing top-level names to src/m64py.egg-info/top_level.txt
reading manifest file 'src/m64py.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.jpg' under directory 'src'
warning: no previously-included files matching '*' found under directory 'dist'
warning: no previously-included files matching '*' found under directory 'test'
writing manifest file 'src/m64py.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
error: could not create 'build/bdist.linux-x86_64/egg': Permission denied

the dependencies are installed

**Comment by faizu396** [comment]
Hopefully you've already figured this out, but just adding `sudo` before `python setup.py install` should give you permission to create files (so just run `sudo python setup.py install`)

**Comment by gen2brain** [comment]
Now there is a Flatpak available here https://flathub.org/apps/net.sourceforge.m64py.M64Py .
