### ISSUE TITLE
M64py crashes when opening ROM.

### ISSUE THREAD

**Issue by OmarRod1314** [mupen64plus/mupen64plus-ui-python#189]
The log doesn't even registers anything else than this, help. I've already tested Rice Video and Glide64mk2, none of them works.
![image](https://user-images.githubusercontent.com/61260071/135765713-ee440ada-6b60-4bc5-8891-72976745f1bb.png)

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
