### ISSUE TITLE
No N64 Controller image on windows

### ISSUE THREAD

**Issue by Unounited** [mupen64plus/mupen64plus-ui-python#193]
So I got this on windows and I saw that the n64 controller image was missing, here's a screenshot:
![image](https://user-images.githubusercontent.com/76746346/148570735-bc5206d3-8cb0-4c92-88f8-13661c5af56f.png)  is there a way to add the image to the program, or do I have to report it?

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
