### ISSUE TITLE
setup.py not recognizing PyQt5

### ISSUE THREAD

**Issue by faizu396** [mupen64plus/mupen64plus-ui-python#195]
I'm trying to install on Raspberry Pi OS (64 bit).
I installed PyQt5 using `sudo apt-get install python3-pyqt5`.
This is what I get when running `python setup.py build`:
`running build
running build_qt
Traceback (most recent call last):
  File "/home/pi/Downloads/m64py/setup.py", line 382, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pi/Downloads/m64py/setup.py", line 372, in run
    self.run_command("build_qt")
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pi/Downloads/m64py/setup.py", line 83, in run
    self.compile_ts(os.path.join(dirpath, filename))
  File "/home/pi/Downloads/m64py/setup.py", line 63, in compile_ts
    import PyQt5
ModuleNotFoundError: No module named 'PyQt5'`
Is there any way to get the setup script to use the version of PyQt5 I installed?

**Comment by faizu396** [comment]
I don't even know if you _can_ install m64py on Raspberry Pi OS since the raspberry pi uses ARM and not x86 or x64

**Comment by Unounited** [comment]
Your incorrect you actually can do this on a Pi It only works on Rasbian buster: https://forums.raspberrypi.com/viewtopic.php?t=313193

**Comment by Unounited** [comment]
> I don't even know if you _can_ install m64py on Raspberry Pi OS since the raspberry pi uses ARM and not x86 or x64, but oh well

you are kind of incorrect, you actually can do this on a Pi 4, however It only works on Rasbian buster, cus bullseye had errors that were not compiling mupen64plus, just follow my guide here and use rasbian buster: https://forums.raspberrypi.com/viewtopic.php?t=313193

**Comment by Unounited** [comment]
> I'm trying to install on Raspberry Pi OS (64 bit). I installed PyQt5 using `sudo apt-get install python3-pyqt5`. This is what I get when running `python setup.y build`: `running build running build_qt Traceback (most recent call last): File "/home/pi/Downloads/m64py/setup.py", line 382, in <module> setuptools.setup( File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup return distutils.core.setup(**attrs) File "/usr/lib/python3.9/distutils/core.py", line 148, in setup dist.run_commands() File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands self.run_command(cmd) File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command cmd_obj.run() File "/home/pi/Downloads/m64py/setup.py", line 372, in run self.run_command("build_qt") File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command self.distribution.run_command(command) File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command cmd_obj.run() File "/home/pi/Downloads/m64py/setup.py", line 83, in run self.compile_ts(os.path.join(dirpath, filename)) File "/home/pi/Downloads/m64py/setup.py", line 63, in compile_ts import PyQt5 ModuleNotFoundError: No module named 'PyQt5'` Is there any way to get the setup script to use the version of PyQt5 I installed?

try `python3 steup.py build` instead

**Comment by Unounited** [comment]
> I don't even know if you _can_ install m64py on Raspberry Pi OS since the raspberry pi uses ARM and not x86 or x64, but oh well

you are kind of incorrect, you actually can do this on a Pi 4, however It only works on Rasbian buster, cus bullseye had errors that were not compiling mupen64plus, just follow my guide here and use rasbian buster: https://forums.raspberrypi.com/viewtopic.php?t=313193

**Comment by faizu396** [comment]
Ok, thanks

**Comment by faizu396** [comment]
Now that I think about it, it probably doesn't matter if it's ARM or x86 or x64 because it all just uses python
