### ISSUE TITLE
Weird issue with StarFox64

### ISSUE THREAD

**Issue by MrF10w** [mupen64plus/mupen64plus-ui-python#198]
Hello,

I hope, I have come to the right place. If not, I apologize and would be grateful if one could point me to a more suitable place.

I have a strange issue with Starfox64 where I can't get a lock on an enemy with a charged laser. That problem does not occur with the same game dump on Retroarch with a Mupen64Plus Next core.

Has anyone encountered this too and has solved it?

Thanks in advance
Mr Flow

**Comment by gen2brain** [comment]
Sorry, not the right place.
