### ISSUE TITLE
Getting "You have to run setup.py build first" using AUR package

### ISSUE THREAD

**Issue by snesgx** [mupen64plus/mupen64plus-ui-python#199]
Using:

https://aur.archlinux.org/m64py.git

and:

https://aur.archlinux.org/python-pysdl2.git

ArchLinux fully updated before proceeding.

```
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.5

You have to run setup.py build first
```

**Comment by gen2brain** [comment]
Where is the issue, it literally tells you what needs to be done? The exact instructions are in the Install section of README.

**Comment by gen2brain** [comment]
Sure, I understood later, but if about AUR, the maintainer of that package should take a look, it is not really an issue with this repo.

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed. The new pyproject.toml method is not used.
