### ISSUE TITLE
m64py crashes when opening input config (Arch)

### ISSUE THREAD

**Issue by autofire372** [mupen64plus/mupen64plus-ui-python#211]
M64Py - A frontend for Mupen64Plus version 0.2.5

Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.9
Frontend: INFO: includes support for Dynamic Recompiler.
Core: Using full mem base
Frontend: DEBUG: override_vidext()
Frontend: WARNING: INPUT_INVALID: An input function parameter is logically invalid
Input: Using auto-config file at: '/usr/local/share/mupen64plus/InputAutoCfg.ini'
Input: parsing error in AnalogDeadzone parameter for controller 1
Input: parsing error in AnalogPeak parameter for controller 1
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/m64py-0.2.5-py3.10.egg/m64py/frontend/input.py", line 85, in show_dialog
    self.set_items()
  File "/usr/lib/python3.10/site-packages/m64py-0.2.5-py3.10.egg/m64py/frontend/input.py", line 93, in set_items
    self.set_opts(), self.set_keys()
  File "/usr/lib/python3.10/site-packages/m64py-0.2.5-py3.10.egg/m64py/frontend/input.py", line 241, in set_opts
    spin1.setValue(int(paramX))
ValueError: invalid literal for int() with base 10: '"4096'

InputAutCfg.ini had nothing to do with this, actually - m64py crashes with the same error without it.

**Comment by gen2brain** [comment]
Looks like you have `'"4096'` in the config, not auto-config, it is not related.

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
