### ISSUE TITLE
Black screen after loading ROM

### ISSUE THREAD

**Issue by ilciavo** [mupen64plus/mupen64plus-ui-python#216]
On OSX Monterrey, I installed m64py with pip and the requirements with homebrew. After starting I get the following log 

> qt.qpa.window: <QNSWindow: 0x7ff6d56e48a0; contentView=<QNSView: 0x7ff6d56e4490; QCocoaWindow(0x600002012e10, window=QWidgetWindow(0x60000333e280, name="QGLWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
> qt.qpa.window: <QNSWindow: 0x7ff6d51833f0; contentView=<QNSView: 0x7ff6d517cda0; QCocoaWindow(0x600002019340, window=QWidgetWindow(0x60000333edc0, name="QStackedWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
> Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0
> Frontend: INFO: includes support for Dynamic Recompiler.
> Core: Unable to open rom database file '/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/Resources/mupen64plus.ini'.
> Frontend: INFO: video extension enabled
> Input: Couldn't open config file '/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/Resources/InputAutoCfg.ini'
> Input: missing 'plugged' parameter from config section AutoConfig0. Setting to 1 (true).
> Input: missing 'plugin' parameter from config section AutoConfig0. Setting to 1 (none).
> Input: missing config key 'DPad R' for controller 1 button 0
> Input: missing config key 'DPad L' for controller 1 button 1
> Input: missing config key 'DPad D' for controller 1 button 2
> Input: missing config key 'DPad U' for controller 1 button 3
> Input: missing config key 'Start' for controller 1 button 4
> Input: missing config key 'Z Trig' for controller 1 button 5
> Input: missing config key 'B Button' for controller 1 button 6
> Input: missing config key 'A Button' for controller 1 button 7
> Input: missing config key 'C Button R' for controller 1 button 8
> Input: missing config key 'C Button L' for controller 1 button 9
> Input: missing config key 'C Button D' for controller 1 button 10
> Input: missing config key 'C Button U' for controller 1 button 11
> Input: missing config key 'R Trig' for controller 1 button 12
> Input: missing config key 'L Trig' for controller 1 button 13
> Input: missing config key 'Mempak switch' for controller 1 button 14
> Input: missing config key 'Rumblepak switch' for controller 1 button 15
> Input: missing config key 'X Axis' for controller 1 axis 0
> Input: missing config key 'Y Axis' for controller 1 axis 1

After loading the ROM, I get a black screen and the following log.
<img width="321" alt="Screen Shot 2023-04-01 at 21 59 42" src="https://user-images.githubusercontent.com/2780595/229311710-02de6b28-1e1b-49dd-bfd4-f9002718f690.png">
> Input: 1 controller(s) found, 1 plugged in and usable in the emulator
> Input: Couldn't open rumble support for joystick #1
> Input: Couldn't open rumble support for joystick #2
> Input: Couldn't open rumble support for joystick #3
> Input: Couldn't open rumble support for joystick #4
> Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
> Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
> Frontend: INFO: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
> Video: Could not open .ini file: RiceVideoLinux.ini
> Video: Unable to read ini file from disk
> Video: ROM (CRC d4c77725aeaa8fd1-50) not found in INI file
> Video: Enabled hacks for game: 'MARIOKART64'
> Video: Initializing OpenGL Device Context.
> qt.qpa.drawing: Display non non-main thread! Deferring to main thread
> Video: Using OpenGL: Intel Inc. - Intel(R) Iris(TM) Graphics 540 : 2.1 INTEL-18.8.6
> Audio: Initializing SDL audio subsystem...
> Input: Couldn't open rumble support for joystick #1
> Input: Couldn't open rumble support for joystick #2
> Input: Couldn't open rumble support for joystick #3
> Input: Couldn't open rumble support for joystick #4
> Core: Could not construct face from /usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/Resources/font.ttf
> Core: Starting R4300 emulator: Dynamic Recompiler
> Core: R4300: starting 64-bit dynamic recompiler at: 0x128521ec1 

The sound is working

**Comment by gen2brain** [comment]
Please try with the new release.
