### ISSUE TITLE
m64py loses configured paths (wayland)

### ISSUE THREAD

**Issue by thesourcehim** [mupen64plus/mupen64plus-ui-python#217]
When run under wayland session (Fedora 37), m64py loses confgured paths after being launched 2 times after paths are set in config. I.e. I configure paths, close main window, the paths are saved into ~/.config/m64py/m64py.conf. Next time I run m64py everything is ok, but then I run it one more time and all paths are overwritten to empty lines and m64py complains about core library not found.

**Comment by gen2brain** [comment]
This should be fixed, please try with the new version.
