### ISSUE TITLE
screen flickering with rice, out of place with glide

### ISSUE THREAD

**Issue by johnny-mac** [mupen64plus/mupen64plus-ui-python#219]
I could've sworn there was an interface in m64py that let you set the controls. I am trying to get a D-pad on a XBOX One S controller(wired) to work with mupen but it doesn't read the axis for some reason, I can bind the D-pad to other buttons and it'll work. Axis 6 & 7, they just don't do anything. I was really hoping this app would have an easy way to set that stuff.

**Comment by johnny-mac** [comment]
OK, I found the input settings that shows the controller mapping... but clicking buttons does nothing, like m64py doesn't recognize the controller. I've got everything working on mupen but this D-pad.

**Comment by johnny-mac** [comment]
Kirby 64 & The Crystal Shards, first game I tried, flickers nonstop.

**Comment by gen2brain** [comment]
Sorry, I don't follow the issue here, you didn't find settings, then you find it, then some unrelated questions about video plugins, etc. This is not a forum, it is for issues with e.g. in this case UI code. Is there an issue with UI code?

**Comment by johnny-mac** [comment]
> Sorry, I don't follow the issue here, you didn't find settings, then you find it, then some unrelated questions about video plugins, etc. This is not a forum, it is for issues with e.g. in this case UI code. Is there an issue with UI code?

why does your emulator recognize a D-pad as a "hat" when every other emulator recognizes it as an axis? The video plugins in m64py don't work on either Void or Artix so you have some kind of problem with your code. It works to configure controls thankfully.

**Comment by johnny-mac** [comment]
Installed manually on Void and through the AUR on Artix and they both do the same thing so you tell me what the issue is.
