### ISSUE TITLE
Crash when opening video plugin options a second time

### ISSUE THREAD

**Issue by codl** [mupen64plus/mupen64plus-ui-python#220]
Steps to reproduce:
1. Open M64py
2. Open plugin settings
3. Click "Configure" in the video section
4. Close the resulting window
5. Click "Configure" in the video section again

M64Py crashes. The only thing the console says is `Unhandled Python exception`. I've been able to reproduce this consistently with both mupen64plus-video-rice.so and mupen64plus-video-glide64mk2.so.

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
