### ISSUE TITLE
Menus greyed out even though emulation is running

### ISSUE THREAD

**Issue by codl** [mupen64plus/mupen64plus-ui-python#221]
It's possible to get M64Py in a state where menu options that should be available during emulation (like pause, stop, save/load state, etc) are greyed out even though emulation is running.

Steps to reproduce:
1. Open M64Py
2. Open a rom
3. Before emulation launches, open any dropdown menu

Once the game starts, most of the menu options will now remain greyed out as if no game was running, even after closing and reopening the menu. Also items in the "settings" menu will remain accessible even though they should not be when a game is running. Because the "Stop" option is greyed out, the only way out of that state seems to be to quit M64Py entirely.

Here's a video demonstrating the issue:

https://github.com/mupen64plus/mupen64plus-ui-python/assets/315139/4893da5e-165c-48f8-864c-1ffe1a3f6c17

**Comment by codl** [comment]
#158 and #167 sound related. But as long as I don't open any menus while emulation is starting then I don't encounter the issue.

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
