### ISSUE TITLE
Ubuntu 22.04.3 LTS : no screenshot view in rom list 

### ISSUE THREAD

**Issue by Estariel** [mupen64plus/mupen64plus-ui-python#222]
hello, 
in Ubuntu 22.04.3 LTS, when i use menu : file  -> open rom -> from list.
in list of rom, all game dont have screenshot f game i right section.

can yu help me ?

**Comment by gen2brain** [comment]
Hello, if you installed it from the repository then the images are not included (not legal), and I preferred not to fetch them from the internet. You can create `~/.local/share/mupen64plus/snapshot and title directory, and copy images from src/m64py/ui/snapshot and title.

**Comment by gen2brain** [comment]
I have added the snapshots tarball in releases with a few instructions on where to extract the archive.
