### ISSUE TITLE
setup.py can't find lrelease despite existing on the system.

### ISSUE THREAD

**Issue by ShimmerFairy** [mupen64plus/mupen64plus-ui-python#225]
Attempting to run `python setup.py build` results in the following error message:

```
running build
running build_qt
warning: BuildQt: Unable to find Qt's Linguist lrelease or lrelease-qt5 tools
```

What's strange is that the program does in fact exist on my system, under `/usr/lib64/qt5/bin/lrelease`, and is definitely used by other software on my system (since I don't have need for it myself), so the setup script is incorrectly missing it for some reason.

**Comment by gen2brain** [comment]
It is expected that the tool is available in PATH, not just installed "somewhere".

**Comment by ShimmerFairy** [comment]
From what I can tell, this is installed to a standard-for-Qt location, and it seems like build tools are expected to find it themselves, rather than relying on it being in `PATH`. After a lot of looking around, it seems like `QLibraryInfo` will tell you what directory Qt binaries are installed in, which should be the best way to find them in any scenario. I can try to figure out how to fix the build script with this and submit a pull request later, but it would likely be faster for somebody more experienced with Python to make this kind of change.
