### ISSUE TITLE
Error running python3 setup.py install: ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by andresgarcia0313** [mupen64plus/mupen64plus-ui-python#229]
### Issue Title:
**Error running `python3 setup.py install`: ModuleNotFoundError: No module named 'distutils'**

### Issue Description:
When attempting to run `python3 setup.py install` in the directory `/home/andres/m64py/mupen64plus-ui-python`, the following error occurs:

```
Traceback (most recent call last):
  File "/home/andres/m64py/mupen64plus-ui-python/setup.py", line 13, in <module>
    import distutils
ModuleNotFoundError: No module named 'distutils'
```

To resolve this issue, I initially tried to install `python3-distutils-extra` using the following command:

```
sudo apt install python3-distutils-extra
```

The installation was successful with no errors reported. However, upon running `python3 setup.py install` again, the error persists:

```
Traceback (most recent call last):
  File "/home/andres/m64py/mupen64plus-ui-python/setup.py", line 13, in <module>
    import distutils
ModuleNotFoundError: No module named 'distutils'
```

I then attempted to install `python3-distutils`, but received a message indicating that the package does not exist in my Kubuntu 24.04 environment.

### Steps to Reproduce:
1. Clone the `mupen64plus-ui-python` repository.
2. Navigate to the `mupen64plus-ui-python` directory.
3. Execute `python3 setup.py install`.

### Proposed Solution:
A solution is needed to ensure that the `distutils` module is properly configured and accessible for `python3` in the specified `m64py-env` environment.

### Environment:
- **Operating System:** Kubuntu 24.04
- **Python:** python3

Any further assistance in resolving this issue would be greatly appreciated. Thank you! 🚀
(m64py-env) andres@lenovoazul:~/m64py/mupen64plus-ui-python$ python3 setup.py install
Traceback (most recent call last):
  File "/home/andres/m64py/mupen64plus-ui-python/setup.py", line 13, in <module>
    import distutils
ModuleNotFoundError: No module named 'distutils'
(m64py-env) andres@lenovoazul:~/m64py/mupen64plus-ui-python$ sudo apt-cache search python3-distutils
python3-distutils-extra - enhancements to the Python3 build system
(m64py-env) andres@lenovoazul:~/m64py/mupen64plus-ui-python$ sudo apt install python3-distutils-extra
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
Se instalarán los siguientes paquetes adicionales:
  intltool
Paquetes sugeridos:
  devscripts
Se instalarán los siguientes paquetes NUEVOS:
  intltool python3-distutils-extra
0 actualizados, 2 nuevos se instalarán, 0 para eliminar y 4 no actualizados.
Se necesita descargar 66,7 kB de archivos.
Se utilizarán 279 kB de espacio de disco adicional después de esta operación.
¿Desea continuar? [S/n] S
Des:1 http://archive.ubuntu.com/ubuntu noble/universe amd64 intltool all 0.51.0-6 [44,6 kB]
Des:2 http://archive.ubuntu.com/ubuntu noble/universe amd64 python3-distutils-extra all 3.0 [22,1 kB]
Descargados 66,7 kB en 1s (63,8 kB/s)              
Seleccionando el paquete intltool previamente no seleccionado.
(Leyendo la base de datos ... 418489 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../intltool_0.51.0-6_all.deb ...
Desempaquetando intltool (0.51.0-6) ...
Seleccionando el paquete python3-distutils-extra previamente no seleccionado.
Preparando para desempaquetar .../python3-distutils-extra_3.0_all.deb ...
Desempaquetando python3-distutils-extra (3.0) ...
Configurando intltool (0.51.0-6) ...
Configurando python3-distutils-extra (3.0) ...
Procesando disparadores para man-db (2.12.0-4build2) ...
(m64py-env) andres@lenovoazul:~/m64py/mupen64plus-ui-python$ python3 setup.py installTraceback (most recent call last):
  File "/home/andres/m64py/mupen64plus-ui-python/setup.py", line 13, in <module>
    import distutils
ModuleNotFoundError: No module named 'distutils'
(m64py-env) andres@lenovoazul:~/m64py/mupen64plus-ui-python$

**Comment by gen2brain** [comment]
That one is complicated, python 3.12 removed distutils, but they still can be used via setuptools or something similar, it is a mess. Anyway, distutils are not used anymore.
