### ISSUE TITLE
angrylion-rdp-plus shows black screen

### ISSUE THREAD

**Issue by shinslashisuka** [mupen64plus/mupen64plus-ui-python#234]
[angrylion-rdp-plus](https://github.com/ata4/angrylion-rdp-plus)
This plugin runs perfect on 0.25. But in 0.30 only shows black screen

**Comment by gen2brain** [comment]
It works here just fine. So there is nothing in the output, something that tells you that you are not using the correct RSP plugin for LLE, something like `Video: HLE video emulation not supported, please use a LLE RSP plugin like mupen64plus-rsp-cxd4`? Surely, there is some output; nobody can guess what is happening without any info.

**Comment by shinslashisuka** [comment]
thx 
I add mupen64plus-rsp-cxd4 then all done.
