### ISSUE TITLE
Module import error, can't start.

### ISSUE THREAD

**Issue by aaroneusthegreat** [mupen64plus/mupen64plus-ui-python#32]
I downloaded the latest source and ran the install script, it threw an error during the install process, but it appeared to create the m64py executable so I tried to run it, and got some more errors. The full output is as follows:

pi@raspberrypi ~/m64py/mupen64plus-ui-python $ python ./setup.py install
running install
running build
running build_qt
error: No such file or directory
pi@raspberrypi ~/m64py/mupen64plus-ui-python $ ./m64py 

---

|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ | |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ | '_ | || |_| |_) | | | | / **| 
| |  | | |_| | |_) |  __/ | | | (_) |**   _|  __/| | |_| __ \ 
|_|  |_|__,_| .**/ _**|_| |_|_**/   |_| |_|   |_|\**,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.2

Traceback (most recent call last):
  File "./m64py", line 83, in <module>
    main()
  File "./m64py", line 67, in main
    from m64py.frontend.mainwindow import MainWindow
  File "/home/pi/m64py/mupen64plus-ui-python/src/m64py/frontend/mainwindow.py", line 24, in <module>
    from m64py.frontend.dialogs import *
  File "/home/pi/m64py/mupen64plus-ui-python/src/m64py/frontend/dialogs.py", line 22, in <module>
    from m64py.ui.about_ui import Ui_AboutDialog
ImportError: No module named about_ui

Any help with this would be greatly appreciated!

**Comment by gen2brain** [comment]
Closing this. Please open new issue if it happens again, with new information.
