### ISSUE TITLE
Custom resolution reset when settings are opened

### ISSUE THREAD

**Issue by Mushman** [mupen64plus/mupen64plus-ui-python#34]
If a custom resolution is specified in `mupen64plus.cfg` located in the Windows AppData folder with either `ScreenWidth` or `ScreenHeight` and any of M64Py's Settings dialogues are opened, the custom resolution is reset. If a game is launched without opening any settings, the custom resolution is used as expected.

An example reproduction of this issue would be to change `ScreenWidth` to `854` and `ScreenHeight` to `480`, launch M64Py, select `Settings` > `Paths`, close the window and launch a game.

**Comment by gen2brain** [comment]
New version is released that fixes this issue.
