### ISSUE TITLE
m64 core issue on freebsd

### ISSUE THREAD

**Issue by goraxmax** [mupen64plus/mupen64plus-ui-python#35]
on freebsd
i have installed
devel/sdl20
devel/py-qt4

, the dependencies needed in order to install m64py

next i Run _python setup.py install_ to install

just below the result : 
"
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    from m64py.core.defs import FRONTEND_VERSION
  File "/mupen64plus-ui-python-master/src/m64py/core/defs.py", line 19, in <module>
    from m64py.platform import DLL_EXT
ImportError: cannot import name DLL_EXT
"

could you help ?

**Comment by gen2brain** [comment]
openbsd support was added like this https://github.com/mupen64plus/mupen64plus-ui-python/pull/1/commits/656ada7b85e7fdee8a05e19b85ff9bd4e13e534b . Similar is probably needed for freebsd.
