### ISSUE TITLE
v0.2.2 no menus on Mac

### ISSUE THREAD

**Issue by triantos** [mupen64plus/mupen64plus-ui-python#40]
On 10.10.2, m64py opens its window, but the menus remain for whatever app was previously running. Clicking on the finder (or any non-m64py window) and then back to m64py fixes this issue.

Maybe related, or maybe not, but when I launch a game, m64py plays the audio, but draws no graphics. When I run with mupen64plus on the same machine, it seems to work fine.

**Comment by gen2brain** [comment]
I can't currently test but I hope Qt5 will solve menus issues. In earlier osx versions I remember that _raise() was needed for app and menus to appear. I plan to release new version after mupen64plus is released. 

Regarding your other problem, can you paste what is logged? Do you use same plugins in m64py?

**Comment by triantos** [comment]
Thanks for the quick reply. Logs below. My exact command line to run when not using m64py is:

./mupen64plus.app/Contents/MacOS/mupen64plus --corelib \
      ./mupen64plus.app/Contents/MacOS/libmupen64plus.dylib --plugindir  \
      ./mupen64plus.app/Contents/MacOS --gfx mupen64plus-video-glide64mk2 --fullscreen

m64py log:

Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.0.0
Frontend: INFO: includes support for Dynamic Recompiler.
Frontend: INFO: video extension enabled
Core: Goodname: Legend of Zelda, The - Ocarina of Time (U) (V1.2) [!]
Core: Name: THE LEGEND OF ZELDA 
Core: MD5: 57A9719AD547C516342E1A15D5C28C3D
Core: CRC: 693ba2ae b7f14e9f
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 33554432 bytes (or 32 Mb or 256 Megabits)
Core: Version: 1449
Core: Manufacturer: 43
Core: Country: Unknown (0x245)
Frontend: INFO: ScreenSaver disabled
Video: opening /Applications/M64Py.app/Contents/Resources/Glide64mk2.ini

Video: 3DNOW! detected.

Frontend: INFO: using Video plugin: 'Glide64mk2 Video Plugin' v2.0.0
Frontend: INFO: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.0.0
Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Forcing default keyboard configuration
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.0.0 initialized.
Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.0.0
Frontend: INFO: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.0.0
Video: Using TEXUMA extension.

Video: InitCombine() 
Video: extensions 
Video: initialized.
Video: 

Audio: Initializing SDL audio subsystem...
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x1081c360

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
