### ISSUE TITLE
x64 support

### ISSUE THREAD

**Issue by Papermanzero** [mupen64plus/mupen64plus-ui-python#41]
Currently m64py doesn't work with x64 builds.
Due to the SDL2 change, there are only x64 builds available.

If a user exchanges the files of m64py with an x64build of Mupen64plus, the emulator won't load any rom or m64py won't boot at all.

**Comment by conchurnavid** [comment]
About which builds are you talking?

The only one I know of for windows is https://bitbucket.org/ecsv/mupen64plus-mxe-daily
But this one has 32 bit and 64 bit builds: https://bitbucket.org/ecsv/mupen64plus-mxe-daily/get/2015-03-16.zip

**Comment by conchurnavid** [comment]
Just tested with the build I know. I've install m64py 0.2.2 and copied the content from ecsv-mupen64plus-mxe-daily-975af7fb5fd2/i686-w64-mingw32 to the m64py installation folder (overwriting the content from m64py).

It still seemed to work. So maybe you can provide a link to your build.

And i think it is ok that m64py doesn't support the x86_64-w64-mingw32 build. A 32 bit binary cannot load 64 bit dlls. For the support it would have to be rebuild as 64 bit binary - but then it cannot support the 32 bit dlls. And the x86_64-w64-mingw32 is also slower. Not sure why it is build for windows.

**Comment by Papermanzero** [comment]
I tested with m64py 0.2.2 and this commit: 
https://bitbucket.org/ecsv/mupen64plus-mxe-daily/commits/7a49a5e2e65a5fadc0fef3562aedcc34b0b95b8b

If i am using i686-w64-mingw32, I cannot boot any rom.
If i am using x86_64-w64-mingw32, m64py won't start.

I did exactly the same what you did. 
But if I understood you correctly. The x86_64-w64-mingw32 is only generating 64bit dlls.
The executable is 32bit. Then it is clear, why it doesn't work.
The only question is why i686-w64-mingw32 is not opening a rom. I will try again and keep you updated.

**Comment by Papermanzero** [comment]
Tried again. Same issue.
M64py starts but rom cannot be loaded.
Here the log:
------------------------------------------------------------------------------------------------
Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.0.0
Frontend: INFO: includes support for Dynamic Recompiler.
Core: Goodname: Legend of Zelda, The - Ocarina of Time (E) (M3) (V1.0) [!]
Core: Name: THE LEGEND OF ZELDA 
Core: MD5: E040DE91A74B61E3201DB0E2323F768A
Core: CRC: B044B569 373C1985
Core: Imagetype: .z64 (native)
Core: Rom size: 33554432 bytes (or 32 Mb or 256 Megabits)
Core: Version: 1449
Core: Manufacturer: Nintendo
Core: Country: Europe (0x50)
Frontend: INFO: ScreenSaver disabled
Video: opening C:\Emulatoren\Mupen64Plus\Glide64mk2.ini

Video: 3DNOW! detected.

Frontend: INFO: using Video plugin: 'Glide64mk2 Video Plugin' v2.0.0
Frontend: INFO: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.0.0
Input: 1 SDL joysticks were found.
Input: N64 Controller #1: Using manual config for SDL joystick 0
Input: N64 Controller #2: Using manual config for SDL joystick 1
Input: 2 controller(s) found, 2 plugged in and usable in the emulator
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open joystick for controller #2: There are 1 joysticks available
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.0.0 initialized.
Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.0.0
Frontend: INFO: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.0.0
Video: Using TEXUMA extension.

Core: Setting video mode: 1280x720
Traceback (most recent call last):
  File "c:\mupen64plus-ui-python.git\dist\windows\build\m64py\out00-PYZ.pyz\m64py.frontend.worker", line 355, in run
  File "c:\mupen64plus-ui-python.git\dist\windows\build\m64py\out00-PYZ.pyz\m64py.core.core", line 346, in execute
WindowsError: exception: access violation reading 0x00000000
-----------------------------------------------------------------------------------------------------------

**Comment by conchurnavid** [comment]
Maybe you can post the output of the log viewer after you've tried to open the rom.

You can also try to start it with --sdl2 as argument for a test. But i don't know why this should change anything. m64py 0.2.2 was already shipped with SDL2 on windows

**Comment by Papermanzero** [comment]
Tried again. Same issue.
M64py starts but rom cannot be loaded.
Here the log:
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.0.0
Frontend: INFO: includes support for Dynamic Recompiler.
Core: Goodname: Legend of Zelda, The - Ocarina of Time (E) (M3) (V1.0) [!]
Core: Name: THE LEGEND OF ZELDA
Core: MD5: E040DE91A74B61E3201DB0E2323F768A
Core: CRC: B044B569 373C1985
Core: Imagetype: .z64 (native)
Core: Rom size: 33554432 bytes (or 32 Mb or 256 Megabits)
Core: Version: 1449
Core: Manufacturer: Nintendo
Core: Country: Europe (0x50)
Frontend: INFO: ScreenSaver disabled
Video: opening C:\Emulatoren\Mupen64Plus\Glide64mk2.ini

Video: 3DNOW! detected.

Frontend: INFO: using Video plugin: 'Glide64mk2 Video Plugin' v2.0.0
Frontend: INFO: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.0.0
Input: 1 SDL joysticks were found.
Input: N64 Controller #1: Using manual config for SDL joystick 0
Input: N64 Controller #2: Using manual config for SDL joystick 1
Input: 2 controller(s) found, 2 plugged in and usable in the emulator
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open joystick for controller #2: There are 1 joysticks available
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.0.0 initialized.
Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.0.0
Frontend: INFO: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.0.0
Video: Using TEXUMA extension.

Core: Setting video mode: 1280x720
Traceback (most recent call last):
File "c:\mupen64plus-ui-python.git\dist\windows\build\m64py\out00-PYZ.pyz\m64py.frontend.worker", line 355, in run
File "c:\mupen64plus-ui-python.git\dist\windows\build\m64py\out00-PYZ.pyz\m64py.core.core", line 346, in execute
WindowsError: exception: access violation reading 0x00000000
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by conchurnavid** [comment]
Thanks, can you try to use rice as video plugin?

**Comment by Papermanzero** [comment]
Haha. Yes, that's it.
With Rice it's working.
Log here:
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.0.0
Frontend: INFO: includes support for Dynamic Recompiler.
Core: Goodname: Legend of Zelda, The - Ocarina of Time (E) (M3) (V1.0) [!]
Core: Name: THE LEGEND OF ZELDA 
Core: MD5: E040DE91A74B61E3201DB0E2323F768A
Core: CRC: B044B569 373C1985
Core: Imagetype: .z64 (native)
Core: Rom size: 33554432 bytes (or 32 Mb or 256 Megabits)
Core: Version: 1449
Core: Manufacturer: Nintendo
Core: Country: Europe (0x50)
Frontend: INFO: ScreenSaver disabled
Frontend: INFO: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.0.0
Frontend: INFO: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.0.0
Input: 1 SDL joysticks were found.
Input: N64 Controller #1: Using manual config for SDL joystick 0
Input: N64 Controller #2: Using manual config for SDL joystick 1
Input: 2 controller(s) found, 2 plugged in and usable in the emulator
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open joystick for controller #2: There are 1 joysticks available
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.0.0 initialized.
Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.0.0
Frontend: INFO: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.0.0
Video: SSE processing enabled.
Video: ROM (CRC 69b544b085193c37-50) not found in INI file
Video: Enabled hacks for game: 'THE LEGEND OF ZELDA'
Video: Initializing OpenGL Device Context.
Core: Setting 32-bit video mode: 1280x720
Video: Failed to set GL_SWAP_CONTROL to 0. (it's 24)
Video: Failed to set GL_BUFFER_SIZE to 32. (it's 24)
Video: Failed to set GL_DEPTH_SIZE to 16. (it's 24)
Video: Using OpenGL: NVIDIA Corporation - GeForce GTX 760/PCIe/SSE2 : 4.5.0 NVIDIA 347.09
Audio: Initializing SDL audio subsystem...
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open joystick for controller #2: There are 1 joysticks available
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Core: Starting R4300 emulator: Dynamic Recompiler
Core: Stopping emulation.
Core: R4300 emulator finished.
Core: Rom closed.
Frontend: INFO: ScreenSaver enabled
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
