### ISSUE TITLE
Xbox 360 Controller Windows

### ISSUE THREAD

**Issue by phly95** [mupen64plus/mupen64plus-ui-python#42]
2 major issues with Xbox 360 controllers on windows
1. The controller key mapping does not work (try it yourself for details: Windows 8.1 M64py, latest version)
2. there is no rumble configuration like n-rage on project64

**Comment by DoctorWho11** [comment]
0.2.1 doesn't have the issue with controller mapping. It's just 0.2.2 that does currently. As for rumble. IMHO not a major issue if controller mapping isn't working ;) But I've reported this issue a while back and it's not even fixed yet.

**Comment by gen2brain** [comment]
Fixed in new release.

**Comment by Catarax** [comment]
Despite booting with Rumble Pack option, MP64Py 2.4 is still able to find save at startup (on Controller 1). 
Nothing happens when I switch to Rumble Pack, no rumble, don't know if there is a message.

360 controller wireless on Windows 10.
