### ISSUE TITLE
Disable ScreenSaver does not work with Xfce

### ISSUE THREAD

**Issue by sergiobenrocha2** [mupen64plus/mupen64plus-ui-python#44]
"Disable ScreenSaver" does not work with Xfce.

M64Py git version, Xubuntu 14.04, 64 bits.

**Comment by sergiobenrocha2** [comment]
Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files

**Comment by gen2brain** [comment]
You will have to install package that provides org.freedesktop.ScreenSaver service, gnome-screensaver, kscreensaver, cinnamon-screensaver, mate-screensaver etc. I didn't used xfce for some time but as I remember they didn't have something like xfce-screensaver, and plain xscreensaver package will not provide dbus service.

**Comment by sergiobenrocha2** [comment]
Xubuntu does not use xscreensaver, instead it uses Light Locker.

**Comment by gen2brain** [comment]
So Xubuntu by default doesn't use screensavers. That light locker is just a locker, replace it with something else if you want that to work. Anyway, nothing I can do there, M64Py uses freedesktop standard and Xubuntu/Light Locker doesn't implement it.

**Comment by sergiobenrocha2** [comment]
Are you sure it does not implement freedesktop standard? It's a fork from gnome-screensaver:

https://github.com/the-cavalry/light-locker

**Comment by gen2brain** [comment]
I am not sure, looks like it doesn't, but whatever, it is out of scope for m64py, try to ask them what is with  org.freedesktop.ScreenSaver service. I don't think there is xubuntu specific way to enable/disable ss, this is standard, and it works where available.

**Comment by sergiobenrocha2** [comment]
It seems it's already implemented, but not in 14.04:

https://github.com/the-cavalry/light-locker/commit/dfcfc9834241225c4bd9fccc9a77714a183b805c

Thanks!
