### ISSUE TITLE
Black screen with Mupen64Plus 2.5 (rice video plugin)

### ISSUE THREAD

**Issue by Pulfer** [mupen64plus/mupen64plus-ui-python#46]
When "Enable Video Extension" is checked, I get black screen (sometimes turning white) instead of proper video rendering.

There's a log line that may be important:
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined

When "Enable Video Extension" is turned off, the rendering is properly done in new window.

Video: Using OpenGL: NVIDIA Corporation - GeForce GTS 250/PCIe/SSE2 : 3.3.0 NVIDIA 340.76

Mupen64Plus 2.5, m64py 0.2.3, python-qt5 5.4, qt5 5.4.1. Linux, 32 bit.

**Comment by Pulfer** [comment]
Maybe it happens because embedded window size in m64py doesn't match video renderer resolution.

**Comment by gen2brain** [comment]
Try to install python-opengl (pyopengl). There is still hack in place for that in vidext.py , and it was needed on debian/ubuntu.

**Comment by Pulfer** [comment]
Thanx, installing python-opengl resolved the issue :-)
