### ISSUE TITLE
Cannot start a game from m64py

### ISSUE THREAD

**Issue by PGPereira** [mupen64plus/mupen64plus-ui-python#53]
Core: Goodname: Legend of Zelda, The - Ocarina of Time (U) (V1.0) [!]
Core: Name: THE LEGEND OF ZELDA 
Core: MD5: 5BD1FE107BF8106B2AB6650ABECD54D6
Core: CRC: ec7011b7 7616d72b
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 33554432 bytes (or 32 Mb or 256 Megabits)
Core: Version: 1449
Core: Manufacturer: 43
Core: Country: USA
Frontend: INFO: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.0.0
Frontend: INFO: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.0.0
Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Forcing default keyboard configuration
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input: Mupen64Plus SDL Input Plugin version 2.0.0 initialized.
Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.0.0
Frontend: INFO: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.0.0
Video: SSE processing enabled.
Video: Found ROM 'THE LEGEND OF ZELDA', CRC b71170ec2bd71676-45
Video: Enabled hacks for game: 'THE LEGEND OF ZELDA'
Video: Initializing OpenGL Device Context.
Cannot make QOpenGLContext current in a different thread
[1]    25132 abort (core dumped)  m64py

**Comment by gen2brain** [comment]
What is your OS, graphic card and Qt version? Also, you are using old mupen64plus, which version of m64py you use?

**Comment by PGPereira** [comment]
OS: Arch Linux (kernel linux-ck 4.0.4)
Graphic Card: nvidia 720m, using bumblebee driver.
QT5: 5.4.1
QT4: 4.8.6
m64py: 0.2.3

**Comment by PGPereira** [comment]
Using the git version of Mupen the program had worken like a charm. Thank you.
