### ISSUE TITLE
System Folder for M64Py Files

### ISSUE THREAD

**Issue by Papermanzero** [mupen64plus/mupen64plus-ui-python#55]
This is not a bug but a feature request.
Due to the amount of python and qt5 files, it would be greate to move all this files in a separate folder to get a better overview in the root of the application folder (like a system or core folder).

**Comment by gen2brain** [comment]
That is how Pyinstaller works, I guess it is not possible without some custom hook. I will check if this is still the case.

**Comment by Papermanzero** [comment]
Thanks a lot for your efforts. Maybe this is supportive:
http://stackoverflow.com/questions/11322538/including-a-directory-using-pyinstaller

**Comment by gen2brain** [comment]
New release is uploaded. Looks much better now.
