### ISSUE TITLE
Controller Setup is not working properly

### ISSUE THREAD

**Issue by Papermanzero** [mupen64plus/mupen64plus-ui-python#56]
It seems the settings from the mupen64plus.cfg files are not detected and set properly.
If a user tries to change the controller configuration from Manual to Automatic, M64Py doesn't save this change to the cfg.
Also a feature to map multiple buttons to the N64 Controller would be good.

**Comment by aeturnum** [comment]
I see the following stack trace when I try to save any changes to controller settings (os x - 10.10, mpy 0.2.3):
Traceback (most recent call last):
  File "/Users/milann/Projects/mupen64plus-ui-python.git/src/m64py/frontend/input.py", line 61, in closeEvent
  File "/Users/milann/Projects/mupen64plus-ui-python.git/src/m64py/frontend/input.py", line 135, in save_config
  File "/Users/milann/Projects/mupen64plus-ui-python.git/src/m64py/frontend/input.py", line 243, in save_opts
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by Yui12** [comment]
I was able to solve this by editing the mupen64plus.cfg that can be found in Users, HP, AppData, Roaming, Mupen64Plus. If your not on windows 7, then just search for Mupen64plus.cfg. I change the file extention to .ini and open it with wordpad. 

I go down to [Input-SDL-Control1] in the cfg file and I edit these files for myself:

Controller configuration mode is set mode 1 which is Auto with named SDL Device. You can set it to fully manual which is 0 and edit the controller if your controller is not supported in the emulator. 

Specifies which joystick is bound to this controller: I set it to 1, but if you're using one controller on your PC then set it to 0.

SDL joystick name (or Keyboard) I set it as the name of the controller I'm using.

**Comment by gen2brain** [comment]
It should be fixed in new release.

**Comment by Yui12** [comment]
Yes thanks for fixing it. I lost hope that anyone would. Now I don't have to jump hoops any longer to get this working. Just have to figure out the perfect controller axis which is something I can do on my own.
