### ISSUE TITLE
Error at compile: No such file or directory

### ISSUE THREAD

**Issue by andoruB** [mupen64plus/mupen64plus-ui-python#57]
So I've tried compiling the other components from this repo, and they all worked fine, except the python front-end, here's what I get when I try to do what the instructions lead me to: 

```
$ python setup.py installrunning install
running build
running build_qt
error: [Errno 2] No such file or directory
```

Am I missing some package?

**Comment by captbrogers** [comment]
Do you have the `python-qt5-devel` package installed?

**Comment by andoruB** [comment]
I can't seem to find such a package under Debian, is it something to do with Python bindings to QT5?

**Comment by chrisnoisel** [comment]
I have the same error. I'm on Debian Jessie, I've tried with both python-pyqt5 and pyqt5-dev.
libsdl1.2debian and libsdl2-2.0-02 are there as well.

**Comment by zryan3** [comment]
I think I am getting a similar error

```
running install
running build
running build_qt
error: [Errno 2] No such file or directory: 'pyrcc5'
```

I'm on Linux Mint 17.2, and I installed PyQt5 using the command `apt-get install python3-pyqt5
`

**Comment by Ok-** [comment]
@zryan3 I had the same problem and I installed this package:
`sudo apt-get install pyqt5-dev-tools`

**Comment by zryan3** [comment]
@Ok- 

I got it working. For reference, the complete list of packages that I needed to install on a fresh Linux Mint 17.3 install were `sudo apt-get install python-pyqt5 pyqt5-dev-tools python-pyqt5.qtopengl libsdl2-dev libsdl2-dbg libsdl2-2.0-0` (well the debug and dev SDL libraries may not have been necessary).

**Comment by chozabu** [comment]
`sudo apt-get install python-pyqt5 pyqt5-dev-tools python-pyqt5.qtopengl libsdl2-dev `

@gen2brain could we get this in the readme?  the .deb package does not install for me (KDE Neon, based on ubuntu 16.04) but after running the above line I was able to happily compile and run m64py

**Comment by gen2brain** [comment]
Ok, added Ubuntu instructions in README. Everything works, you don't have issues like in #91 ?

**Comment by gen2brain** [comment]
@chozabu Also, do you remember what was the error when you tried to install .deb ?

**Comment by chozabu** [comment]
@gen2brain I do not seem to have the issues from #91 
As for the errors installing the deb file - sorry to say, but it seems to have worked correctly this time!
```
$ sudo dpkg -i m64py_0.2.4-0_all.deb 
Selecting previously unselected package m64py.
(Reading database ... 356944 files and directories currently installed.)
Preparing to unpack m64py_0.2.4-0_all.deb ...
Unpacking m64py (0.2.4-0) ...
dpkg: dependency problems prevent configuration of m64py:
 m64py depends on python3-opengl; however:
  Package python3-opengl is not installed.
 m64py depends on python3-pyqt5.qtopengl; however:
  Package python3-pyqt5.qtopengl is not installed.
 m64py depends on python3-pyqt5.qtsvg; however:
  Package python3-pyqt5.qtsvg is not installed.
 m64py depends on python3-sdl2; however:
  Package python3-sdl2 is not installed.

dpkg: error processing package m64py (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 m64py
```

followed by an `sudo apt install -f` and It seems to have installed the deb.

I suspect the issue was fixed by a change made to get it building
