### ISSUE TITLE
grrr

### ISSUE THREAD

**Issue by slimjim27** [mupen64plus/mupen64plus-ui-python#59]
ok so here's my dilema. Im trying to get m64py to save my manual controller config but it seems to not like me because it keeps reverting to auto config as soon as i leave controller input configuration. im using a snakebyte usb ps3 controller v1.1 ive looked through as many forums as i could find but im still coming up empty. also just to clarify ive tried to change the settings in autoconfig.ini except i cant seem to find it i look for my mupen64plus folder under /usr/share/ and all i find is m64py is it possible any one can help me because i take pride in my intellegence and right now i feel like a total imbecile

**Comment by kirbyfan64** [comment]
Try checking `~/.config/mupen64plus`.

**Comment by slimjim27** [comment]
i figured it out but thanks though it was under /usr/share/games/mupen64plus took me what felt like ages to find it edit it and then get the emu to actually play my daggum games. although if you could help me again id appreciate it. ok so im running a celeron d dual core 3.5ghz processor with 2 1GB vram cards and i have a sony graphics card but it doesnt seem to work. should i spend the money for parts or get parts for my old amd (had xp on it, power wont kick on at all, but i have an ati rage home theater i can put in it when i get it running and i need 3 ddr3 vram cards). and another thing the amd is older than my compaq,s celeron d (sorry i forgot to mention above) but i know amd is best for gaming. im just wondering parts for celeron or amd?

**Comment by kirbyfan64** [comment]
Woah...I'd think any graphics card should work. I use my laptop's built-in one. I mean, these are N64 games, not FF XIV or something like that...
