### ISSUE TITLE
M64py not detecting additional inputs

### ISSUE THREAD

**Issue by bankrobber725** [mupen64plus/mupen64plus-ui-python#60]
Wondering if you can help me with an issue. Fairly new to this mupen64 + m64py thing, but I'm trying to use 4 controllers with m64py, but I'm only getting the GUI to detect 2 of them. Any ideas on how to config either mupen or m64py to support additional (total of 4) USB controllers? 

Thanks.

![screen shot 2015-10-19 at 12 56 04 pm](https://cloud.githubusercontent.com/assets/15200720/10586221/c8fd094a-7660-11e5-89e8-b757e0257c86.png)

**Comment by Unounited** [comment]
click on controller 1 on the top left and you should see 2, 3, and 4.
