### ISSUE TITLE
GlideN64 is crashing M64Py

### ISSUE THREAD

**Issue by Papermanzero** [mupen64plus/mupen64plus-ui-python#64]
I downloaded the newest version of GlideN64 from emucr.
The issue is that M64Py is accessing a memory section which is invalid.
So if the user selects GlideN64 as gpu plugin and start a rom, the screen turns for a moment black and returns to M64Py splash screen. The log shows that an invalid memory access occurred.
I will post the log as soon as I have time.

**Comment by Papermanzero** [comment]
Here the Log:

Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0
Frontend: INFO: includes support for Dynamic Recompiler.
Input: Using auto-config file at: '.../Mupen64Plus/core\InputAutoCfg.ini'
Input: Using auto-config file at: '.../Mupen64Plus/core\InputAutoCfg.ini'
Input: Using auto-config file at: '.../Mupen64Plus/core\InputAutoCfg.ini'
Core: Goodname: Legend of Zelda, The - Majora's Mask (E) (M4) (V1.0) [!]
Core: Name: ZELDA MAJORA'S MASK 
Core: MD5: 13FAB67E603B002CEAF0EEA84130E973
Core: CRC: E97955C6 BC338D38
Core: Imagetype: .z64 (native)
Core: Rom size: 33554432 bytes (or 32 Mb or 256 Megabits)
Core: Version: 144B
Core: Manufacturer: Nintendo
Core: Country: Europe (0x50)
Frontend: INFO: ScreenSaver disabled
Frontend: INFO: using Video plugin: 'GLideN64' v2.0.0
Frontend: INFO: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
Input: 1 SDL joysticks were found.
Input: N64 Controller #1: Using manual config for SDL joystick 0
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input: Couldn't open rumble support for joystick #1
Input: Couldn't open rumble support for joystick #2
Input: Couldn't open rumble support for joystick #3
Input: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
Frontend: INFO: using RSP plugin: 'Static Interpreter' v0.1.1
Core: Setting video mode: 1920x1080
Traceback (most recent call last):
  File "...\mupen64plus-ui-python.git\src\m64py\frontend\worker.py", line 354, in run
  File "...\mupen64plus-ui-python.git\src\m64py\core\core.py", line 346, in execute
OSError: exception: access violation reading 0x00000001

**Comment by gen2brain** [comment]
Works for me with latest GlideN64 compiled from source. Although I had to export this on Linux because I have intel graphic card, without it all I get is black screen:

export MESA_GL_VERSION_OVERRIDE=3.3COMPAT

**Comment by Papermanzero** [comment]
I think it was an issue with GlideN64. Because this issue did not occur anymore after several changes in GlideN64.
