### ISSUE TITLE
No Reliable way to uninstall

### ISSUE THREAD

**Issue by CptMonkeyFist** [mupen64plus/mupen64plus-ui-python#68]
You have a lot of commands in the setup.py file, but uninstall isn't one of them. I have used the install command, but got frustrated with options not working as expected and would like to go back to command line. Unfortunately your setup script doesn't seem to provide an uninstall option and your sparse documentation says nothing about uninstallation. My only option is to reverse engineer the setup.py file and try to undo the steps it took during installation. Considering the unsurprising lack of documentation and comments, this is rather difficult. If you are going to add an "install" option then you should provide an "uninstall" option.

**Comment by gen2brain** [comment]
You should not use manual install if you need reverse engineering later to uninstall.

Setup works same as in all other python apps, there is no uninstall, but you can save list of files like this:
    python setup.py install --record files.txt 
and it will install to default lib/python/site-packages like all other python apps, binary will be in /usr/bin, .desktop file and icon in /usr/share etc. that is standard.

deb, rpm, exe and dmg packages are available for download, that code in setup.py is used to build packages, and you can uninstall those packages.

Also, you could just start app from unpacked archive, there was no need to install if you only wanted to try it.

**Comment by CptMonkeyFist** [comment]
All valid points. I was unaware of the file list as it isn't obvious from the help documentation. I will use that in the future. I should have tried running it from the unpacked archive first, but just followed the readme without considering it. On a better note the frustration I was having was with the Glide plugin and not M64PY. Once I played around with other plugin settings I was able to get it working without an issue. Still you may want to add the uninstallation instructions to the Readme.

**Comment by sabudum** [comment]
So, is there a way to uninstall?

**Comment by JakobWilly171** [comment]
Hey guys maybe someone already offered this as an alternative, I struggled really hard with Uninstalling mupen64plus, however, i think i found something that works. so mupen can be opened and read like any other file directory, well if you try to uninstall it simply says you don't have permission, and if you go to control panel you can never find it, if you use commands it doesn't work, well out of frustration I went into mupens file directory and out of desperation tried to delete some of its core components, guess what it worked, even if the file keeps you from uninstalling, if you just open the file and delete all of its component folders under program files in windows you can essentially render its non functional lol! and then just remove the program normally.
