### ISSUE TITLE
"Mupen64Plus library not found."

### ISSUE THREAD

**Issue by zilti** [mupen64plus/mupen64plus-ui-python#71]
This is all I get from m64py. Even when I set the correct path in the configuration file and everything. I'm on the latest release.

**Comment by gen2brain** [comment]
Can you paste console output/log. What do you have in config file, and where is your library located.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
