### ISSUE TITLE
New release binary builds (was: 'bytes' has no attribute 'encode' on Input configuration)

### ISSUE THREAD

**Issue by cookiengineer** [mupen64plus/mupen64plus-ui-python#78]
Steps to reproduce:
- Go to Settings / Plugins
- Configure Input
- In new Window select Fully Manual, change some things, Close.

```
Traceback (most recent call last):
  File "/usr/share/m64py/m64py/frontend/input.py", line 61, in closeEvent
    self.save_config()
  File "/usr/share/m64py/m64py/frontend/input.py", line 135, in save_config
    self.save_opts()
  File "/usr/share/m64py/m64py/frontend/input.py", line 243, in save_opts
    self.config.set_parameter("name", devicename.encode())
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by cookiengineer** [comment]
Nevermind, I fixed it by merging this line into my local installation: https://github.com/mupen64plus/mupen64plus-ui-python/blob/master/src/m64py/frontend/input.py#L247

So I guess the issue here is that a new release build (deb/rpm packages) are needed :)

**Comment by Yutsa** [comment]
So you had to download the source code ?

**Comment by cookiengineer** [comment]
Yes, source code in repo is working. Deb/RPM package release is out of date.

**Comment by gen2brain** [comment]
New release is uploaded.
