### ISSUE TITLE
More input issues

### ISSUE THREAD

**Issue by DonaldKBrown** [mupen64plus/mupen64plus-ui-python#81]
I'm unable to use a USB controller with M64Py, if I click "close" in "fully manual", nothing changes.

```
Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.0.0
Frontend: INFO: includes support for Dynamic Recompiler.
Frontend: INFO: includes support for MIPS r4300 Debugger.
Frontend: INFO: video extension enabled
Traceback (most recent call last):
  File "/usr/share/m64py/m64py/frontend/input.py", line 61, in closeEvent
    self.save_config()
  File "/usr/share/m64py/m64py/frontend/input.py", line 135, in save_config
    self.save_opts()
  File "/usr/share/m64py/m64py/frontend/input.py", line 243, in save_opts
    self.config.set_parameter("name", devicename.encode())
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by Insidious611** [comment]
Was just about to open a bug with the exact same issue, glad someone else is having it. I was actually able with some luck to somehow force it to use my USB controller in "Fully Automatic" mode, but I still can't use the config window for the input plugin with my controller connected, or at least, if I do, nothing changes (therefore I can't manually change assignments etc) and the log shows the exact same error Donald got, about bytes having no attribute encode.

**Comment by gen2brain** [comment]
Try with new release, should be fixed.
