### ISSUE TITLE
All Paths are blank

### ISSUE THREAD

**Issue by SaltyRaichu** [mupen64plus/mupen64plus-ui-python#84]
Hello, I'm on mac. all of my paths are blank, and I don't know the directories.

**Comment by djlalo08** [comment]
This same thing happened to me. Everything was working fine, except the resolution was off. Then the game (Ocarina of Time) got stuck when I tried going fullscreen. I eventually powered my mac off. When I restarted it, all the file paths were blank and I got the error "Mupen64Plus library not found". I tried downloading both m64py and mupen64plus and it didn't help.

**Comment by gen2brain** [comment]
There is no need to download mupen64plus, it is included in .app dir. Config file is in ~/Library/Preferences/com.m64py.m64py.plist. Just remove it, it probably happens when you change location of M64Py.app dir.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
