### ISSUE TITLE
How do I reset the whole thing back to when I first used it (Mint 18)

### ISSUE THREAD

**Issue by White-waluigi** [mupen64plus/mupen64plus-ui-python#85]
I tried reinstalling it, sudo apt-get purging it, removed all the /usr/share and plugin folders, etc... , but now it wont even start anymore, so how do I reset this thing again?

**Comment by gen2brain** [comment]
Well, you probably need to reinstall everything, also mupen64plus and plugins, all that you deleted manually.
Config for m64py is in ~/.config/m64py, for mupen64plus in ~/.config/mupen64plus , I guess you wanted to reset config only.

**Comment by White-waluigi** [comment]
Thanks, I think everything is reset now, but no still no games giving video with the rice plugin and some are broken on glide, but that seams to be a mupen64 issue, thanks thought

**Comment by White-waluigi** [comment]
FIxed he rice plugin, had to set the screen update to ai origin uöpdate, thanks
