### ISSUE TITLE
Unhandled Python extension when trying to open input configuration.

### ISSUE THREAD

**Issue by MightyAlex200** [mupen64plus/mupen64plus-ui-python#87]
First I tried changing the input configuration on the AUR  0.2.3-5 version. Worked, but when I closed the configuration it just closed the entire program. This was supposedly fixed in commit 6179216 so I tried the m64py-git package in AUR. The configuration closed correctly, but about 2 seconds later it crashed. After that no matter which version I used (including most recent git version) it would always crash when I press the configure button. Trying it with sudo yielded the same result. Here is the output I get.

```
$ sudo ./m64py
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.3

Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
Frontend: INFO: No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
ldd: warning: you do not have execution permission for `/usr/lib/libmupen64plus.so.2.0.0'
Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0
Frontend: INFO: includes support for Dynamic Recompiler.
Frontend: INFO: video extension enabled
Unhandled Python exception
[1]    12088 abort      sudo ./m64py
```

**Comment by rhinoceraptor** [comment]
I'm running into the same issue.

**Comment by gen2brain** [comment]
Can you try with 0.2.4 ?

**Comment by andyklimczak** [comment]
I can reproduce this by not having the controller previously configured plugged in (m64py 0.2.4, mupen64plus 2.5.0)

Either plug in the controller that was previously configured so the input mapper doesn't crash, or remove the previous configs (wherever those live)

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.

**Comment by djbusby** [comment]
I've just tried the freshest bits from this package and still get the crash when opening input settings.  It's only when the controllers are not active.  I'm using xbox360 wireless and the xpad kernel drivers.
