### ISSUE TITLE
SDL configure control (Aborted) linux

### ISSUE THREAD

**Issue by aluismarte** [mupen64plus/mupen64plus-ui-python#92]
Crash on click configure control.

**Comment by gen2brain** [comment]
What version do you use, some info, crash info, anything?

**Comment by aluismarte** [comment]
Version 0.2.4

This is normally a bug in some application using the D-Bus library.
process 18971: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../../dbus/dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.
Unhandled Python exception
Aborted

Linux Debian Stretch

**Comment by gen2brain** [comment]
Duplicate of #91 .
