### ISSUE TITLE
Opening issue M64py (please help ASAP) 

### ISSUE THREAD

**Issue by SomeEmuUser** [mupen64plus/mupen64plus-ui-python#96]
I know this question has been asked (https://github.com/mupen64plus/mupen64plus-ui-python/issues/29) but it has not resolved my issue.

I was playing the most recent version on my 2015 Macbook pro 10.12.3. Everything was working fine. Then I accidentally clicked the Library when trying to set a ROM destination, next thing I know, it goes to the menu where everything is blank and you can't click anything. I have deleted, restarted, re download. I have deleted the .plist (unless there was one I missed). Then I took the same files, put it on my family's IMac and it worked perfectly (as the pictures included show). Is there anything I can do? Thanks. 

![img_1878](https://cloud.githubusercontent.com/assets/25572644/23038545/47cc5354-f43f-11e6-98e4-bac6dd4f506d.JPG)
![img_1879](https://cloud.githubusercontent.com/assets/25572644/23038546/47d1f412-f43f-11e6-88eb-6c419d39d95b.JPG)

**Comment by gen2brain** [comment]
You should delete .plist from ~/Library/Preferences/com.m64py.m64py.plist.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
