### ISSUE TITLE
i can't install on Debian Stretch (i tried on repo stable)

### ISSUE THREAD

**Issue by otgo** [mupen64plus/mupen64plus-ui-python#98]
Seleccionando el paquete m64py previamente no seleccionado.
(Leyendo la base de datos ... 346445 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar m64py_0.2.4-0_all (1).deb ...
Desempaquetando m64py (0.2.4-0) ...
Preparando para desempaquetar m64py_0.2.4-0_all.deb ...
Desempaquetando m64py (0.2.4-0) sobre (0.2.4-0) ...
¡Se ha desempaquetado más de una copia del paquete m64py!
 Se configurará solamente una vez.
dpkg: problemas de dependencias impiden la configuración de m64py:
 m64py depende de libsdl2-dev; sin embargo:
  El paquete `libsdl2-dev' no está instalado.
 m64py depende de python3-opengl; sin embargo:
  El paquete `python3-opengl' no está instalado.
 m64py depende de python3-pyqt5.qtopengl; sin embargo:
  El paquete `python3-pyqt5.qtopengl' no está instalado.
 m64py depende de python3-pyqt5.qtsvg; sin embargo:
  El paquete `python3-pyqt5.qtsvg' no está instalado.

dpkg: error al procesar el paquete m64py (--install):
 problemas de dependencias - se deja sin configurar
Procesando disparadores para man-db (2.7.6.1-2) ...
Procesando disparadores para desktop-file-utils (0.23-1) ...
Procesando disparadores para gnome-menus (3.13.3-8) ...
Procesando disparadores para mime-support (3.60) ...
Se encontraron errores al procesar:
 m64py

Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
El paquete libsdl2-dev no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

E: El paquete «libsdl2-dev» no tiene un candidato para la instalación

**Comment by gen2brain** [comment]
As I understand (hard to read non-english errors) it is complaining that libsdl2-dev package doesn't exists. Don't know much about debian repos, but it should be there https://packages.debian.org/stretch/libsdl2-dev .

**Comment by Danielpok** [comment]
Tienes que instalar las dependencias en este caso intenta con `sudo apt install python3-opengl` y para eso tienes que tener instalado python3 , y tiene otras dependencias que es pyqt5 `sudo apt install python3-pyqt5` y si no lo soluciona tiene otra dependencia que tienes uqe instalar que viene en la pagina de el ui como dependencies
